#!/usr/bin/env node
// Writes apps/bot/src/features/brands.generated.mjs from the API's DEFAULT_BRANDS.
//
// Why a generated copy: the bot image is built from apps/bot alone (see its Dockerfile), so
// the bot cannot import apps/api at run time. Two hand-kept lists had already drifted (the bot
// knew roblox and dis.gd, the API knew google, apple, stripe and the site's own brand). The
// list lives in ONE place, apps/api/src/lib/moderation/links.mjs; this copies it, and
// apps/api/test/moderation-brands-drift.test.mjs fails while the copy is stale.
//
//   node apps/bot/scripts/sync-brands.mjs          (from BCWEB) rewrite the copy
//   node apps/bot/scripts/sync-brands.mjs --check  exit 1 if the copy is stale
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
export const OUT = join(HERE, '../src/features/brands.generated.mjs');
const SOURCE = join(HERE, '../../api/src/lib/moderation/links.mjs');

/** DEFAULT_BRANDS ([{ brand, domains }]) → the module text. Pure: the drift test calls it. */
export function renderBrands(list) {
  const merged = new Map();
  for (const b of list) {
    const key = String(b.brand).toLowerCase();
    const cur = merged.get(key) || [];
    for (const d of b.domains) if (!cur.includes(d)) cur.push(d);
    merged.set(key, cur);
  }
  const lines = [...merged].map(([k, v]) => `  ${JSON.stringify(k)}: [${v.map((d) => JSON.stringify(d)).join(', ')}],`);
  return [
    '// GENERATED by apps/bot/scripts/sync-brands.mjs from DEFAULT_BRANDS in',
    '// apps/api/src/lib/moderation/links.mjs. Do not edit: change that list, then run',
    '// `node apps/bot/scripts/sync-brands.mjs` from BCWEB (a test fails while this copy is stale).',
    '//',
    '// brand -> the domains that really belong to it (look-alike check, features/automod.mjs).',
    'export const BRANDS = Object.freeze({',
    ...lines,
    '});',
    '',
  ].join('\n');
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const { DEFAULT_BRANDS } = await import(pathToFileURL(SOURCE).href);
  const want = renderBrands(DEFAULT_BRANDS);
  let have = '';
  try { have = readFileSync(OUT, 'utf8').replace(/\r\n/g, '\n'); } catch { /* not written yet */ }
  if (process.argv.includes('--check')) {
    if (have !== want) { console.error('brands.generated.mjs is stale: run node apps/bot/scripts/sync-brands.mjs'); process.exit(1); }
    console.log('brands.generated.mjs is up to date');
  } else if (have === want) {
    console.log('brands.generated.mjs already up to date');
  } else {
    writeFileSync(OUT, want);
    console.log(`wrote ${OUT}`);
  }
}
