// The bot's button icons, as a set of PNGs an admin uploads to the application's emoji page
// (Discord Developer Portal → the app → Emojis), then names in the dashboard as <:name:id>.
// Drawn with canvas vectors — no font, no asset — so the pack is generated by the API on
// demand and always matches the list of keys the bot uses (ICONS below).
//
// One key per button the bot draws. The `fallback` is the unicode emoji used until an admin
// maps a custom one; `label` is what the dashboard shows beside the field.
export const ICONS = Object.freeze({
  level: { fallback: '⭐', label: 'My level', color: '#f59e0b' },
  shop: { fallback: '🛒', label: 'Shop', color: '#3b82f6' },
  inventory: { fallback: '🎒', label: 'Inventory', color: '#8b5cf6' },
  leaderboard: { fallback: '🏆', label: 'Leaderboard', color: '#eab308' },
  casino: { fallback: '🎰', label: 'Casino', color: '#ef4444' },
  again: { fallback: '🔁', label: 'Play again', color: '#10b981' },
  refresh: { fallback: '🔄', label: 'Refresh', color: '#64748b' },
  link: { fallback: '🔗', label: 'Link account', color: '#5865f2' },
  buy: { fallback: '🛍️', label: 'Buy', color: '#22c55e' },
  gift: { fallback: '🎁', label: 'Gift', color: '#ec4899' },
  coin: { fallback: '🪙', label: 'Points / balance', color: '#f59e0b' },
  reveal: { fallback: '✉️', label: 'Reveal a code', color: '#0ea5e9' },
  history: { fallback: '📜', label: 'History', color: '#a16207' },
  enter: { fallback: '🎉', label: 'Enter (giveaway)', color: '#f43f5e' },
  site: { fallback: '🌐', label: 'Open on the site', color: '#0ea5e9' },
  voice: { fallback: '🎙️', label: 'Voice controls', color: '#5865f2' },
  rename: { fallback: '✏️', label: 'Rename', color: '#64748b' },
  limit: { fallback: '👥', label: 'User limit', color: '#64748b' },
  region: { fallback: '🌍', label: 'Region', color: '#0ea5e9' },
  lock: { fallback: '🔒', label: 'Lock', color: '#ef4444' },
  unlock: { fallback: '🔓', label: 'Unlock', color: '#22c55e' },
  private: { fallback: '🙈', label: 'Private', color: '#8b5cf6' },
  public: { fallback: '👁️', label: 'Public', color: '#8b5cf6' },
  claim: { fallback: '🙋', label: 'Claim room', color: '#22c55e' },
  export: { fallback: '📤', label: 'Export preset', color: '#64748b' },
  import: { fallback: '📥', label: 'Import preset', color: '#64748b' },
});

function rounded(x, X, Y, w, h, r) { x.beginPath(); x.moveTo(X + r, Y); x.arcTo(X + w, Y, X + w, Y + h, r); x.arcTo(X + w, Y + h, X, Y + h, r); x.arcTo(X, Y + h, X, Y, r); x.arcTo(X, Y, X + w, Y, r); x.closePath(); }
function star(x, cx, cy, R, r, n = 5) { x.beginPath(); for (let i = 0; i < n * 2; i++) { const a = -Math.PI / 2 + (i * Math.PI) / n; const rr = i % 2 ? r : R; x.lineTo(cx + Math.cos(a) * rr, cy + Math.sin(a) * rr); } x.closePath(); }

// Each glyph is drawn white in a 128×128 frame whose centre is (64, 64).
const GLYPH = {
  level: (x) => { star(x, 64, 66, 40, 18); x.fill(); },
  shop: (x) => { rounded(x, 30, 50, 68, 46, 8); x.fill(); x.lineWidth = 8; x.beginPath(); x.arc(64, 50, 18, Math.PI, 0); x.stroke(); },
  inventory: (x) => { rounded(x, 34, 40, 60, 60, 12); x.fill(); x.lineWidth = 8; x.beginPath(); x.moveTo(48, 40); x.quadraticCurveTo(64, 14, 80, 40); x.stroke(); x.fillStyle = 'rgba(0,0,0,0.25)'; rounded(x, 46, 66, 36, 20, 5); x.fill(); },
  leaderboard: (x) => { x.beginPath(); x.moveTo(36, 30); x.lineTo(92, 30); x.lineTo(84, 74); x.quadraticCurveTo(64, 92, 44, 74); x.closePath(); x.fill(); x.fillRect(56, 84, 16, 14); x.fillRect(42, 96, 44, 10); x.lineWidth = 7; x.beginPath(); x.arc(30, 44, 10, Math.PI * 1.5, Math.PI * 0.5, true); x.arc(98, 44, 10, Math.PI * 0.5, Math.PI * 1.5, true); x.stroke(); },
  casino: (x) => { rounded(x, 28, 36, 72, 56, 10); x.fill(); x.fillStyle = 'rgba(0,0,0,0.3)'; for (let i = 0; i < 3; i++) rounded(x, 36 + i * 20, 46, 14, 36, 3); x.fill(); x.fillStyle = '#fff'; x.beginPath(); x.arc(108, 40, 7, 0, Math.PI * 2); x.fill(); x.fillRect(105, 40, 6, 24); },
  again: (x) => { x.lineWidth = 10; x.beginPath(); x.arc(64, 64, 32, -Math.PI * 0.2, Math.PI * 1.35); x.stroke(); x.beginPath(); x.moveTo(84, 26); x.lineTo(100, 44); x.lineTo(78, 50); x.closePath(); x.fill(); },
  refresh: (x) => { x.lineWidth = 10; x.beginPath(); x.arc(64, 64, 30, Math.PI * 1.1, Math.PI * 1.9); x.stroke(); x.beginPath(); x.arc(64, 64, 30, Math.PI * 0.1, Math.PI * 0.9); x.stroke(); x.beginPath(); x.moveTo(98, 30); x.lineTo(98, 54); x.lineTo(74, 54); x.closePath(); x.fill(); x.beginPath(); x.moveTo(30, 98); x.lineTo(30, 74); x.lineTo(54, 74); x.closePath(); x.fill(); },
  link: (x) => { x.lineWidth = 11; x.lineCap = 'round'; x.beginPath(); x.moveTo(52, 76); x.lineTo(76, 52); x.stroke(); x.beginPath(); x.arc(46, 82, 18, Math.PI * 0.25, Math.PI * 1.25); x.stroke(); x.beginPath(); x.arc(82, 46, 18, Math.PI * 1.25, Math.PI * 2.25); x.stroke(); },
  buy: (x) => { rounded(x, 32, 48, 64, 50, 8); x.fill(); x.lineWidth = 8; x.beginPath(); x.arc(64, 48, 16, Math.PI, 0); x.stroke(); x.strokeStyle = 'rgba(0,0,0,0.35)'; x.lineWidth = 7; x.beginPath(); x.moveTo(50, 74); x.lineTo(60, 84); x.lineTo(80, 64); x.stroke(); },
  gift: (x) => { rounded(x, 30, 56, 68, 44, 6); x.fill(); rounded(x, 26, 42, 76, 18, 5); x.fill(); x.fillStyle = 'rgba(0,0,0,0.3)'; x.fillRect(59, 42, 10, 58); x.fillStyle = '#fff'; x.lineWidth = 7; x.beginPath(); x.arc(52, 32, 10, 0, Math.PI * 2); x.arc(76, 32, 10, 0, Math.PI * 2); x.stroke(); },
  coin: (x) => { x.beginPath(); x.arc(64, 64, 38, 0, Math.PI * 2); x.fill(); x.fillStyle = 'rgba(0,0,0,0.3)'; x.beginPath(); x.arc(64, 64, 26, 0, Math.PI * 2); x.fill(); x.fillStyle = '#fff'; x.font = 'bold 34px sans-serif'; x.textAlign = 'center'; x.textBaseline = 'middle'; x.fillText('$', 64, 66); },
  reveal: (x) => { rounded(x, 24, 40, 80, 52, 8); x.fill(); x.strokeStyle = 'rgba(0,0,0,0.35)'; x.lineWidth = 7; x.beginPath(); x.moveTo(28, 44); x.lineTo(64, 70); x.lineTo(100, 44); x.stroke(); },
  history: (x) => { rounded(x, 34, 26, 60, 76, 6); x.fill(); x.fillStyle = 'rgba(0,0,0,0.3)'; for (let i = 0; i < 4; i++) x.fillRect(44, 40 + i * 14, i === 3 ? 24 : 40, 6); },
  enter: (x) => { x.beginPath(); x.moveTo(40, 100); x.lineTo(28, 40); x.lineTo(76, 68); x.closePath(); x.fill(); for (const [px, py, r] of [[84, 30, 6], [100, 52, 5], [92, 82, 5], [64, 24, 4]]) { x.beginPath(); x.arc(px, py, r, 0, Math.PI * 2); x.fill(); } },
  site: (x) => { x.lineWidth = 8; x.beginPath(); x.arc(64, 64, 36, 0, Math.PI * 2); x.stroke(); x.beginPath(); x.ellipse(64, 64, 16, 36, 0, 0, Math.PI * 2); x.stroke(); x.beginPath(); x.moveTo(28, 64); x.lineTo(100, 64); x.stroke(); },
  voice: (x) => { rounded(x, 50, 24, 28, 50, 14); x.fill(); x.lineWidth = 8; x.beginPath(); x.arc(64, 64, 26, 0, Math.PI); x.stroke(); x.fillRect(60, 90, 8, 12); x.fillRect(46, 100, 36, 7); },
  rename: (x) => { x.save(); x.translate(64, 64); x.rotate(-Math.PI / 4); rounded(x, -10, -40, 20, 64, 4); x.fill(); x.beginPath(); x.moveTo(-10, 28); x.lineTo(10, 28); x.lineTo(0, 44); x.closePath(); x.fill(); x.restore(); },
  limit: (x) => { for (const [cx, s] of [[50, 1], [80, 0.85]]) { x.beginPath(); x.arc(cx, 48, 14 * s, 0, Math.PI * 2); x.fill(); x.beginPath(); x.arc(cx, 96, 26 * s, Math.PI, 0); x.fill(); } },
  region: (x) => { x.lineWidth = 8; x.beginPath(); x.arc(64, 64, 36, 0, Math.PI * 2); x.stroke(); x.beginPath(); x.moveTo(44, 40); x.quadraticCurveTo(64, 52, 56, 72); x.quadraticCurveTo(80, 70, 84, 92); x.stroke(); },
  lock: (x) => { rounded(x, 34, 58, 60, 46, 8); x.fill(); x.lineWidth = 9; x.beginPath(); x.arc(64, 54, 20, Math.PI, 0); x.stroke(); x.fillStyle = 'rgba(0,0,0,0.3)'; x.beginPath(); x.arc(64, 78, 7, 0, Math.PI * 2); x.fill(); },
  unlock: (x) => { rounded(x, 34, 58, 60, 46, 8); x.fill(); x.lineWidth = 9; x.beginPath(); x.arc(64, 44, 20, Math.PI, Math.PI * 1.75); x.stroke(); x.fillStyle = 'rgba(0,0,0,0.3)'; x.beginPath(); x.arc(64, 78, 7, 0, Math.PI * 2); x.fill(); },
  private: (x) => { x.lineWidth = 8; x.beginPath(); x.moveTo(24, 64); x.quadraticCurveTo(64, 96, 104, 64); x.stroke(); x.beginPath(); x.moveTo(36, 44); x.lineTo(92, 84); x.stroke(); },
  public: (x) => { x.lineWidth = 8; x.beginPath(); x.moveTo(24, 64); x.quadraticCurveTo(64, 24, 104, 64); x.quadraticCurveTo(64, 104, 24, 64); x.stroke(); x.beginPath(); x.arc(64, 64, 12, 0, Math.PI * 2); x.fill(); },
  claim: (x) => { x.beginPath(); x.arc(58, 40, 14, 0, Math.PI * 2); x.fill(); x.beginPath(); x.arc(58, 96, 26, Math.PI, 0); x.fill(); x.lineWidth = 9; x.lineCap = 'round'; x.beginPath(); x.moveTo(78, 66); x.lineTo(96, 40); x.lineTo(104, 46); x.stroke(); },
  export: (x) => { rounded(x, 30, 70, 68, 30, 6); x.fill(); x.lineWidth = 10; x.lineCap = 'round'; x.beginPath(); x.moveTo(64, 74); x.lineTo(64, 30); x.stroke(); x.beginPath(); x.moveTo(46, 46); x.lineTo(64, 28); x.lineTo(82, 46); x.stroke(); },
  import: (x) => { rounded(x, 30, 70, 68, 30, 6); x.fill(); x.lineWidth = 10; x.lineCap = 'round'; x.beginPath(); x.moveTo(64, 26); x.lineTo(64, 70); x.stroke(); x.beginPath(); x.moveTo(46, 54); x.lineTo(64, 72); x.lineTo(82, 54); x.stroke(); },
};

/** One icon as a 128×128 PNG buffer. */
export async function renderEmoji(key) {
  const def = ICONS[key];
  if (!def) return null;
  const { createCanvas } = await import('@napi-rs/canvas');
  const c = createCanvas(128, 128); const x = c.getContext('2d');
  // A rounded tile in the key's colour, a soft highlight, then the white glyph.
  rounded(x, 4, 4, 120, 120, 28); x.fillStyle = def.color; x.fill();
  const g = x.createLinearGradient(0, 0, 0, 128); g.addColorStop(0, 'rgba(255,255,255,0.22)'); g.addColorStop(1, 'rgba(0,0,0,0.16)');
  rounded(x, 4, 4, 120, 120, 28); x.fillStyle = g; x.fill();
  x.fillStyle = '#fff'; x.strokeStyle = '#fff'; x.lineJoin = 'round';
  try { GLYPH[key](x); } catch { /* a glyph that fails leaves the coloured tile */ }
  return c.encode('png');
}

/** Every icon, as a zip: <key>.png ×N + a README naming each. */
export async function renderEmojiPack() {
  const { default: archiver } = await import('archiver');
  const chunks = [];
  const zip = archiver('zip', { zlib: { level: 6 } });
  const done = new Promise((res, rej) => { zip.on('data', (d) => chunks.push(d)); zip.on('end', res); zip.on('error', rej); });
  for (const key of Object.keys(ICONS)) {
    const png = await renderEmoji(key);
    if (png) zip.append(png, { name: `bc_${key}.png` });
  }
  zip.append(`BetterCommunity bot icons\n\nUpload every PNG on your application's Emojis page (Discord Developer Portal → your app → Emojis), keeping the file names (bc_<key>). Then, in the admin dashboard → Discord bot → Levels & economy → Button icons, paste each emoji as <:bc_key:ID> (right-click the emoji in Discord → Copy Text, or read the id from the Emojis page).\n\n${Object.entries(ICONS).map(([k, v]) => `bc_${k}.png — ${v.label} (fallback ${v.fallback})`).join('\n')}\n`, { name: 'README.txt' });
  zip.finalize();
  await done;
  return Buffer.concat(chunks);
}
