// The migration history: what each one did, and where the folder and the database disagree.
//
// The schema map already reports index drift between schema.prisma and the SQL. This is the
// other axis — the migrations as a timeline, and the two questions only a live database can
// answer:
//
//   · a migration recorded as APPLIED whose folder is gone. Prisma stores a checksum per
//     migration and re-validates it; a deleted or renamed folder makes every later
//     `migrate deploy` fail, on a machine that is not the one where it was deleted.
//   · a migration on disk that this database has never run. Normal on a fresh checkout,
//     alarming on production.
//
// And one the SQL answers by itself: which migrations are DESTRUCTIVE. `DROP COLUMN` and
// `DROP TABLE` are the statements that lose data rather than change shape, and knowing which
// release contained one is the difference between a restore and a guess.
//
// A small SQL reader rather than a parser: these files are generated by Prisma and use a
// narrow, predictable subset. It reports what it understood, so a statement it cannot read
// shows up as an uncounted operation rather than as a confident wrong answer.

/** Statements worth naming, in the order they are looked for. `DROP` first: a file that both
 *  adds and drops is a destructive migration, and matching ADD first would hide that. */
const OPS = [
  ['dropTable', /^\s*DROP TABLE\b/im],
  ['dropColumn', /^\s*ALTER TABLE\s+\S+\s+DROP COLUMN\b/im],
  ['dropIndex', /^\s*DROP INDEX\b/im],
  ['deleteData', /^\s*DELETE FROM\b/im],
  ['createTable', /^\s*CREATE TABLE\b/im],
  ['addColumn', /^\s*ALTER TABLE\s+\S+\s+ADD COLUMN\b/im],
  // Not DDL. A migration that writes ROWS behaves differently from one that changes shape:
  // it is the kind that cannot simply be re-run, and the kind a restore has to think about.
  // Two of these exist here and both reported as "no operations" before they were counted —
  // an empty result that looked like a clean one.
  ['insertData', /^\s*INSERT INTO\b/im],
  ['updateData', /^\s*UPDATE\s+"/im],
  ['alterColumn', /^\s*ALTER TABLE\s+\S+\s+ALTER COLUMN\b/im],
  ['createIndex', /^\s*CREATE (?:UNIQUE )?INDEX\b/im],
  ['createType', /^\s*CREATE TYPE\b/im],
  ['alterType', /^\s*ALTER TYPE\b/im],
  ['addConstraint', /^\s*ALTER TABLE\s+\S+\s+ADD CONSTRAINT\b/im],
];

/** Counting form of the same patterns — `g` so every occurrence in the file is counted. */
const COUNTERS = OPS.map(([name, re]) => [name, new RegExp(re.source, 'gim')]);

/** Statements that lose data. Everything else changes shape and can be reversed by another
 *  migration; these cannot be, and that is the whole distinction. */
const DESTRUCTIVE = new Set(['dropTable', 'dropColumn', 'deleteData']);

/**
 * One migration folder, read.
 *
 * The name carries the timestamp Prisma generated it with — `20260715013715_repos_list_index`
 * — and that prefix is the ordering. `0_init` has no timestamp and sorts first, which is
 * correct and worth not breaking.
 */
export function parseMigration(name, sql) {
  const text = String(sql);
  const ops = {};
  for (const [op, re] of COUNTERS) {
    const n = (text.match(re) || []).length;
    if (n) ops[op] = n;
  }
  const destructive = Object.keys(ops).filter((o) => DESTRUCTIVE.has(o));
  const m = String(name).match(/^(\d{14})_(.*)$/);
  return {
    name,
    // Kept as the raw digits rather than a Date: this runs on the server and in tests, and a
    // timezone-dependent value in a report about ordering is a bug waiting for a reader in
    // another country.
    stamp: m ? m[1] : null,
    label: m ? m[2] : name,
    ops,
    destructive,
    // Tables touched, for "which migration created this". Deliberately just the quoted
    // identifiers Prisma emits.
    tables: [...new Set([...text.matchAll(/(?:CREATE TABLE|ALTER TABLE)\s+"([^"]+)"/gi)].map((x) => x[1]))],
  };
}

/**
 * The timeline, plus the disagreements.
 *
 * `applied` is the `_prisma_migrations` table: rows of { migration_name, finished_at,
 * rolled_back_at }. Pass an empty array when there is no database — the on-disk half is
 * still an answer, and it is reported as such rather than as "48 migrations pending".
 */
export function buildMigrationMap(onDisk, applied = [], hasDatabase = true) {
  const migrations = onDisk
    .map(({ name, sql }) => parseMigration(name, sql))
    // `0_init` has no timestamp; it is the first one and must stay there.
    .sort((a, b) => String(a.stamp ?? '0').localeCompare(String(b.stamp ?? '0')));

  const diskNames = new Set(migrations.map((m) => m.name));
  const appliedByName = new Map(applied.map((r) => [r.migration_name, r]));

  const pending = hasDatabase ? migrations.filter((m) => !appliedByName.has(m.name)).map((m) => m.name) : [];

  // Applied and no longer on disk. Prisma re-validates a checksum per migration, so this
  // breaks `migrate deploy` on every OTHER machine — the one where the folder was deleted
  // keeps working, which is what makes it hard to notice.
  const appliedNotOnDisk = applied.filter((r) => !diskNames.has(r.migration_name)).map((r) => r.migration_name);

  // Started and never finished, or rolled back: the database is in a state no migration
  // describes, and the next deploy refuses to run at all.
  const unfinished = applied
    .filter((r) => r.rolled_back_at || !r.finished_at)
    .map((r) => ({ name: r.migration_name, rolledBack: !!r.rolled_back_at }));

  const totals = {};
  for (const m of migrations) for (const [op, n] of Object.entries(m.ops)) totals[op] = (totals[op] ?? 0) + n;

  return {
    hasDatabase,
    counts: {
      onDisk: migrations.length,
      applied: applied.length,
      pending: pending.length,
      appliedNotOnDisk: appliedNotOnDisk.length,
      unfinished: unfinished.length,
      destructive: migrations.filter((m) => m.destructive.length).length,
    },
    totals,
    // Newest first — the question is almost always about a recent one.
    timeline: [...migrations].reverse().map((m) => ({
      ...m,
      applied: hasDatabase ? appliedByName.has(m.name) : null,
    })),
    pending,
    appliedNotOnDisk,
    unfinished,
    destructiveMigrations: migrations.filter((m) => m.destructive.length)
      .map((m) => ({ name: m.name, destructive: m.destructive, tables: m.tables })),
  };
}
