[package]
name = "bcweb-native"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2", default-features = false, features = ["napi4"] }
napi-derive = "2"
blake3 = { version = "1", features = ["pure"] }
zip = { version = "2", default-features = false, features = ["deflate"] }
zstd = "0.13"
image = { version = "0.25", default-features = false, features = ["jpeg", "png"] }

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
strip = "symbols"
