/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ZipEntry {
  name: string
  size: number
}
export interface ZipFile {
  name: string
  data: Buffer
}
/** List a zip's entries (name + uncompressed size) on a worker thread. */
export declare function zipEntries(data: Buffer): Promise<unknown>
/**
 * Read a zip's non-directory entries WITH their bytes, on a worker thread. Replaces the
 * adm-zip `new AdmZip(buf)` + per-entry `getData()` parse that blocked the event loop.
 */
export declare function zipReadAll(data: Buffer): Promise<unknown>
/**
 * BLAKE3 hash (hex) of a buffer on a worker thread — INTERNAL integrity only (dedup keys,
 * manifests, cache keys), never the public sha256 API contract.
 */
export declare function blake3Hex(data: Buffer): Promise<unknown>
