// Per-project marketplace (K). A project lists products; a purchase is fulfilled by handing over
// a key (a fixed one, one drawn from a pool, or — later — one generated by an external system),
// some revealed content, or a Discord role. Phase 1: product CRUD, a key pool, and delivery for
// free products (static / pool / content / role). Paid products return `checkout_required` — the
// Stripe one-time flow and the external-key webhook are Phase 2.
import { z } from 'zod';
import crypto from 'node:crypto';
import { db, requireRole, requireEditor, logAudit, clientIp, hasCap, projectGrants, marketRoleGrants } from '../lib/lib.mjs';
import { presignGet, putObject, deleteObject } from '../lib/storage.mjs';
import { sendMail, mailShell, emailEnabled } from '../lib/mail.mjs';
import { stripe, ensureCustomer } from './hosting.mjs';

// What a product HANDS OVER. The first five were the whole of it, and between them they
// could not sell the most ordinary thing a project sells — a file. The workaround was to paste
// a download link into `content`, which makes it a public URL: it is in the buyer's purchase
// row, and in anybody else's the moment they share it, for ever.
//
//   key_static    one key, the same for everyone
//   key_pool      one key drawn from a finite list, claimed race-safely
//   key_license   a UNIQUE key minted per buyer — infinite supply, traceable to the purchase
//   key_external  a key fetched from the project's own system
//   content       revealed text (a code, instructions, a coupon)
//   file          a file held in the platform's own storage, handed over as a SHORT-LIVED
//                 signed URL re-issued per buyer rather than a link that never expires
//   link          a plain URL, as a real button rather than a paragraph
//   role          a Discord role
const DELIVERY_KINDS = ['key_static', 'key_pool', 'key_license', 'key_external', 'content', 'file', 'link', 'role'];
/** Where a product's file lives. Private: nothing under this prefix is publicly served. */
const FILE_PREFIX = 'marketplace';
/** How long a download link stays good. Long enough to click, short enough not to be a
 *  distributable URL — the reason the file kind exists rather than a pasted link. */
const DOWNLOAD_TTL = 600;

/**
 * What the marketplace is allowed to weigh, in MB, and what it weighs now.
 *
 * Every other place a byte can land on this platform is metered — hosted repos have a quota,
 * catalogues draw from a pool, Discord activity has a cap, analytics has a retention. Product
 * files had nothing: a 64 MB body limit per request and no ceiling above it, on the same disk
 * the hosting page sells by the gigabyte. Enough products and the marketplace quietly eats the
 * capacity somebody paid for.
 *
 * One global ceiling rather than a per-project quota, because a product is not attached to a
 * hosting pool — it hangs off a project key — and inventing a second, parallel notion of
 * "this project's storage" is how two numbers that should agree stop agreeing.
 */
const DEFAULT_STORAGE_MB = 2048;
export async function marketplaceStorage(p) {
  const row = await p.adminSetting.findUnique({ where: { key: 'marketplace.storageMB' } }).catch(() => null);
  const capMB = Math.max(0, Number(row?.value ?? DEFAULT_STORAGE_MB) || 0);
  const agg = await p.projectProduct.aggregate({ _sum: { fileBytes: true }, _count: { fileKey: true } });
  const usedBytes = Number(agg._sum.fileBytes || 0);
  return {
    capMB, capBytes: capMB * 1024 * 1024, usedBytes, files: agg._count.fileKey || 0,
    freeBytes: Math.max(0, capMB * 1024 * 1024 - usedBytes),
  };
}

/**
 * The platform's cut of a sale, in basis points (1000 = 10%).
 *
 * THREE levels, most specific first: this product, then the page it is sold on, then the
 * site. Two of them are usually empty — the point is that "our own projects pay nothing" is
 * one decision made once per project rather than remembered on every product added to it,
 * and "this one product is different" stays possible without disturbing the rest.
 *
 * Basis points and not a float: 12.5% is expressible, and no sale is ever off by a rounding
 * error that came from a percentage stored as 0.125000000000000006.
 */
const DEFAULT_FEE_BP = 1000;

/**
 * A basis-point value that is actually usable, or null. Shared by all three levels so they
 * cannot disagree about what counts as "set" — and so that ZERO counts, which is the whole
 * reason the field exists.
 *
 * THE TYPE CHECK IS THE POINT, and its absence was a bug this file shipped with for about ten
 * minutes: `Number(null)`, `Number('')` and `Number([])` are all 0, so a product with no
 * override — the ordinary case — read as "this one is free" and every sale on the platform
 * would have been charged nothing. `Number.isFinite` alone does not save you, because by then
 * the coercion has already happened.
 */
export function validBp(v) {
  if (typeof v !== 'number' && typeof v !== 'string') return null;
  if (typeof v === 'string' && v.trim() === '') return null;
  const n = Number(v);
  return Number.isFinite(n) && n >= 0 && n <= 10000 ? Math.round(n) : null;
}

export async function marketplaceFeeBp(p) {
  const row = await p.adminSetting.findUnique({ where: { key: 'marketplace.feePercentBp' } }).catch(() => null);
  return validBp(row?.value) ?? DEFAULT_FEE_BP;
}

/**
 * How a page is named in the per-project margin map.
 *
 * A product hangs off EITHER a `projectKey` (a fixed project) or a `showcaseProjectId` (a
 * page somebody else's project lives on), and the two id spaces are not the same. Prefixed
 * so a showcase cuid can never collide with a project key, and so a map entry says which
 * kind of page it is about when somebody reads the raw setting.
 */
export function feeScopeOf(product) {
  if (product?.projectKey) return `project:${product.projectKey}`;
  if (product?.showcaseProjectId) return `showcase:${product.showcaseProjectId}`;
  return null;
}

/**
 * May this person administer the marketplace of the page this product sits on?
 *
 * Pure, and separate from the lookups that feed it, because it is the whole permission rule
 * and the expensive way to be wrong about it is one page's manager reaching another page's
 * products — or the money attached to them.
 *
 * It matches on the same two id spaces `feeScopeOf` distinguishes, and never crosses them:
 * a project KEY and a showcase CUID could coincide, and reading one as the other would hand
 * somebody a page they were never granted.
 *
 * `allShowcase` covers every admin-created page and NO fixed project. That is what it has
 * always meant for page and blog rights, and widening it here would quietly promote a
 * showcase moderator to selling on the flagship products.
 *
 * A product attached to no page is reachable only by site-wide power. Otherwise the way to
 * reach every product would be to create one with no page.
 *
 * @param power   { manageAll } — resolved by the caller, because working it out needs the DB
 * @param grants  the union of ProjectPermission rows and market-scoped roles
 * @param product the row being touched
 */
export function marketScopeAllows(power, grants, product) {
  if (power?.manageAll) return true;
  if (!grants) return false;
  // EVERY page the product names, not the first one that answers. This used to return on
  // projectKey and never look at showcaseProjectId — so a grantee for one project page put
  // their own projectKey and somebody else's showcase id in the same body, passed on the
  // first branch, and the product appeared in that page's public shop at their price. The
  // showcase id ALONE was correctly refused; adding a page they owned bypassed the refusal.
  //
  // Written as "no page may be one they lack" rather than "some page may be one they have",
  // which is the same short-circuit wearing different words.
  const pk = product?.projectKey;
  const sc = product?.showcaseProjectId;
  if (!pk && !sc) return false;   // attached to nothing is not attached to everything
  if (pk && !grants.projectKeys?.has(pk)) return false;
  if (sc && !(grants.allShowcase || grants.showcaseIds?.has(sc))) return false;
  return true;
}

/** The per-project overrides: `{ "project:bmm": 0, "showcase:abc123": 500 }`. */
export async function marketplaceFeeByProject(p) {
  const row = await p.adminSetting.findUnique({ where: { key: 'marketplace.feeByProject' } }).catch(() => null);
  const v = row?.value;
  if (!v || typeof v !== 'object' || Array.isArray(v)) return {};
  const out = {};
  for (const [k, raw] of Object.entries(v)) {
    const bp = validBp(raw);
    // A junk entry is DROPPED rather than treated as zero. Zero means "this project pays
    // nothing", which is a decision; a malformed row is not one, and reading it as free is
    // the expensive direction to be wrong in.
    if (bp !== null) out[k] = bp;
  }
  return out;
}

/**
 * What we keep and what the seller is owed, for ONE sale, at the moment of the sale.
 *
 * Rounded DOWN in the platform's favour is the wrong default: it makes the site take the
 * extra cent on every odd amount for ever. `Math.round` splits it, and `netCents` is the
 * subtraction rather than a second percentage, so the two always add back to the price.
 */
export function splitFee(priceCents, feeBp) {
  const price = Math.max(0, Math.round(Number(priceCents) || 0));
  const bp = Math.min(10000, Math.max(0, Math.round(Number(feeBp) || 0)));
  const feeCents = Math.round((price * bp) / 10000);
  return { feeCents, netCents: price - feeCents };
}

/**
 * Where the money goes at the moment it is charged, or null to leave it with the platform.
 *
 * Until this existed the marketplace WROTE the split — feeCents and netCents on every
 * purchase row — and moved none of it. Every cent landed in the platform's Stripe account
 * and those two columns recorded a debt that nothing discharged. Fine while the seller is
 * us; not fine the moment it is anybody else.
 *
 * This is a DESTINATION CHARGE: the buyer pays the platform, Stripe transfers the seller's
 * share to their connected account, and the platform's cut stays behind as an application
 * fee. The alternative — charging directly on the connected account — would put the
 * customer, the price and the dispute on their side of the line, and this platform holds
 * all three.
 *
 * Returns null in five cases, and the fallback in every one of them is the behaviour that
 * existed before: the platform collects, the purchase records that it did, and somebody
 * settles up by hand. A checkout that REFUSES because payouts are not configured would take
 * the marketplace down for every first-party product on the site.
 *
 * The account not being enabled yet is the case worth naming. A connected account exists
 * from the instant onboarding starts and cannot accept a charge until Stripe finishes its
 * checks; routing to one fails the whole session, so the buyer cannot pay at all. Falling
 * back is worse for the seller by a few days and better than a checkout that 500s.
 *
 * @param product  the row being sold — priceCents and billing are read
 * @param seller   the connected account on file for its page, or null
 * @param feeBp    the margin in basis points, from feeForProduct()
 */
/**
 * May this buyer still be handed the file?
 *
 * 'paid' is a one-off purchase (and a free claim). A SUBSCRIPTION is created 'active' by the
 * webhook and set to 'ended' when it lapses. Nothing couples deliveryKind to billing, so a
 * `file` product sold monthly is an ordinary thing to build — and the gate that only accepted
 * 'paid' answered "not_paid" to a customer who was paying, for the whole life of their
 * subscription.
 *
 * 'ended' is refused deliberately and separately: the row is kept so the buyer can see what
 * they had, and the storefront gets to say "your subscription ended" rather than accusing
 * them of not paying. Any status this does not know is refused — a new one is a decision
 * somebody has to come back here and make.
 */
export function mayDownload(status) {
  return status === 'paid' || status === 'active';
}

export function connectChargeParams(product, seller, feeBp) {
  const dest = seller?.stripeAccountId;
  if (!dest || !seller?.chargesEnabled) return null;

  const { feeCents, netCents } = splitFee(product?.priceCents, feeBp);
  // Nothing to route. A free product has no charge to attach a destination to, and a 100%
  // margin leaves the seller nothing — routing anyway would mint a destination transfer of
  // zero and an application fee equal to the whole amount, on every sale, for ever.
  if (netCents <= 0) return null;

  const recurring = product?.billing === 'subscription';
  if (recurring) {
    // A subscription has no single amount to take a fee out of: the price recurs, so Stripe
    // wants a PERCENTAGE applied to each invoice. Sending application_fee_amount here is a
    // 400, and sending the basis points where a percent is expected would ask for 1000%.
    const pct = Math.min(100, Math.max(0, Math.round(Number(feeBp) || 0) / 100));
    return {
      mode: 'subscription',
      subscription_data: {
        // Omitted rather than sent as zero: "this project pays nothing" is a real setting,
        // and its shape on a routed sale is a transfer with no fee attached at all.
        ...(pct > 0 ? { application_fee_percent: pct } : {}),
        transfer_data: { destination: dest },
      },
    };
  }
  return {
    mode: 'payment',
    payment_intent_data: {
      ...(feeCents > 0 ? { application_fee_amount: feeCents } : {}),
      transfer_data: { destination: dest },
    },
  };
}

/**
 * The margin actually charged on this product: its own override, else its page's, else the
 * site default.
 *
 * `??` at every level and never `||`, because ZERO is a valid answer at all three and the
 * one people set on purpose. `||` here would charge the site default on exactly the products
 * meant to be free.
 */
export async function feeForProduct(p, product) {
  const own = validBp(product?.feePercentBp);
  if (own !== null) return own;
  const scope = feeScopeOf(product);
  if (scope) {
    const byProject = await marketplaceFeeByProject(p);
    const forPage = validBp(byProject[scope]);
    if (forPage !== null) return forPage;
  }
  return marketplaceFeeBp(p);
}

/**
 * The connected account that gets paid for this product's page, or null.
 *
 * Scoped with feeScopeOf — the same string the per-project margin uses — so the two
 * decisions about a page, how much we keep and who gets the rest, are made at one level and
 * cannot end up disagreeing about which sale belongs to whom.
 *
 * Never throws. A payee lookup failing must not be able to take a checkout down: the
 * fallback is the platform collecting, which is what happened on every sale before this
 * existed.
 */
export async function sellerForProduct(p, product) {
  const scope = feeScopeOf(product);
  if (!scope) return null;
  return p.marketplaceSeller.findUnique({ where: { scope } }).catch(() => null);
}

/** The Stripe account fields worth mirroring, from an account object. */
export function sellerMirror(acct) {
  return {
    chargesEnabled: !!acct?.charges_enabled,
    payoutsEnabled: !!acct?.payouts_enabled,
    detailsSubmitted: !!acct?.details_submitted,
    country: acct?.country || null,
    // Stripe's own wording, kept verbatim. Paraphrasing it into "not ready" is how an admin
    // screen ends up unable to say what somebody actually has to go and do.
    disabledReason: acct?.requirements?.disabled_reason || null,
    requirements: acct?.requirements ? {
      currently_due: acct.requirements.currently_due || [],
      past_due: acct.requirements.past_due || [],
      pending_verification: acct.requirements.pending_verification || [],
    } : null,
    syncedAt: new Date(),
  };
}

const productSchema = z.object({
  projectKey: z.string().max(60).nullish(),
  showcaseProjectId: z.string().max(60).nullish(),
  name: z.string().min(1).max(120),
  description: z.string().max(2000).optional().default(''),
  priceCents: z.number().int().min(0).max(10_000_00).optional().default(0),
  currency: z.string().max(8).optional().default('usd'),
  active: z.boolean().optional().default(true),
  deliveryKind: z.enum(DELIVERY_KINDS).optional().default('content'),
  staticKey: z.string().max(400).nullish(),
  content: z.string().max(4000).nullish(),
  roleId: z.string().max(32).nullish(),
  fileKey: z.string().max(300).nullish(),
  fileName: z.string().max(200).nullish(),
  linkUrl: z.string().url().max(600).nullish(),
  externalUrl: z.string().url().max(400).nullish(),
  externalSecret: z.string().max(200).nullish(),
  stock: z.number().int().min(0).max(1_000_000).nullish(),
  // Recurring. `intervalMonths` is only read when billing is 'subscription'; 1 and 12 are
  // the two Stripe renders sensibly in a checkout, and anything else is a number a buyer
  // has to do arithmetic on to understand.
  billing: z.enum(['one_time', 'subscription']).optional().default('one_time'),
  intervalMonths: z.number().int().min(1).max(12).nullish(),
  // Where the buyer uses what they bought. Not secret — it is shown on the product page
  // BEFORE the sale too, because "and then what" is a question people want answered first.
  redeemUrl: z.string().url().max(600).nullish(),
  redeemNote: z.string().max(1000).nullish(),
  // Stripped for anyone below SUPERADMIN at the route, never here: a schema that rejected
  // it would turn an ordinary admin's save into a 400 they cannot act on.
  feePercentBp: z.number().int().min(0).max(10000).nullish(),
});

/** Fields only a SUPERADMIN may set. Dropped rather than refused, so an ADMIN editing a
 *  product they can otherwise edit does not get a 400 about a field they never touched. */
function stripPrivileged(data, user) {
  if (user?.role === 'SUPERADMIN') return data;
  const { feePercentBp, ...rest } = data;
  return rest;
}

// What a buyer is allowed to see about a product — never the static key, the pool, the external
// secret, or how many are left beyond "in stock or not".
const pub = (pr) => ({
  id: pr.id, name: pr.name, description: pr.description, priceCents: pr.priceCents, currency: pr.currency,
  deliveryKind: pr.deliveryKind, inStock: pr.stock == null || pr.stock > pr.sold,
  billing: pr.billing || 'one_time', intervalMonths: pr.intervalMonths || null,
  // Shown before the sale as well as after. "What do I do with it once I have paid" is a
  // question people want answered first, and a storefront that only answers it afterwards
  // is one people leave.
  redeemUrl: pr.redeemUrl || null, redeemNote: pr.redeemNote || null,
});

// Ask an external key generator for a code. The admin sets externalUrl + externalSecret; we POST
// a signed body and expect { key } back. Signed with HMAC-SHA256 so the external system can trust
// the request came from us; timed out so a dead endpoint never hangs a purchase.
async function externalKey(product, buyerId) {
  const body = JSON.stringify({ productId: product.id, buyerId, name: product.name, ts: Date.now() });
  const sig = product.externalSecret ? crypto.createHmac('sha256', product.externalSecret).update(body).digest('hex') : '';
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), 10_000);
  try {
    const r = await fetch(product.externalUrl, { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-BC-Signature': sig }, body, signal: ctrl.signal });
    if (!r.ok) { const e = new Error('external_failed'); e.code = 'external_failed'; throw e; }
    const j = await r.json().catch(() => ({}));
    const key = String(j.key || j.code || '').trim();
    if (!key) { const e = new Error('external_no_key'); e.code = 'external_no_key'; throw e; }
    return { key, external: true };
  } catch (e) {
    if (e.code) throw e;
    const err = new Error('external_failed'); err.code = 'external_failed'; throw err;
  } finally { clearTimeout(timer); }
}

// Fulfil a purchase: returns the delivery payload, or throws { code } when it cannot. Exported so
// the Stripe webhook can deliver a paid purchase the same way the free path does.
export async function fulfilProduct(p, product, buyerId) {
  switch (product.deliveryKind) {
    case 'content': return { content: product.content || '' };
    case 'role': return { role: product.roleId || '' };
    case 'key_static': return { key: product.staticKey || '' };
    case 'key_pool': {
      // Claim one unclaimed pool key: pick the oldest free key, mark it. updateMany with a
      // claimedAt:null guard makes the claim race-safe (a second buyer can't take the same key).
      for (let attempt = 0; attempt < 5; attempt++) {
        const free = await p.projectKey.findFirst({ where: { productId: product.id, claimedAt: null }, orderBy: { createdAt: 'asc' } });
        if (!free) { const e = new Error('out_of_stock'); e.code = 'out_of_stock'; throw e; }
        const claimed = await p.projectKey.updateMany({ where: { id: free.id, claimedAt: null }, data: { claimedById: buyerId, claimedAt: new Date() } });
        if (claimed.count === 1) return { key: free.code };
      }
      const e = new Error('out_of_stock'); e.code = 'out_of_stock'; throw e;
    }
    case 'key_license': {
      // A key nobody else has, minted here. Unlike a static key it cannot be shared back into
      // the wild without being traceable, and unlike a pool it never runs out. The alphabet
      // drops the characters people misread out loud (0/O, 1/I/L).
      const A = 'ABCDEFGHJKMNPQRSTUVWXYZ23456789';
      const part = () => Array.from({ length: 5 }, () => A[crypto.randomInt(A.length)]).join('');
      return { key: `${part()}-${part()}-${part()}-${part()}`, licensed: true };
    }
    case 'file':
      // The KEY is stored, never the URL: a signed link is minted per download and expires, so
      // what sits in the purchase row cannot be forwarded to somebody who did not buy it.
      if (!product.fileKey) { const e = new Error('no_file'); e.code = 'no_file'; throw e; }
      return { fileKey: product.fileKey, fileName: product.fileName || 'download' };
    case 'link': return { url: product.linkUrl || '' };
    case 'key_external': return externalKey(product, buyerId);
    default: return {};
  }
}

export default async function marketplaceRoutes(app) {
  // ── Public: a project's live products ──────────────────────────────────────
  app.get('/marketplace/products', async (req) => {
    const p = await db();
    const { projectKey, showcaseProjectId } = req.query || {};
    const where = { active: true };
    if (projectKey) where.projectKey = String(projectKey);
    else if (showcaseProjectId) where.showcaseProjectId = String(showcaseProjectId);
    else return { products: [] };
    const rows = await p.projectProduct.findMany({ where, orderBy: { createdAt: 'desc' }, take: 200 });
    return { products: rows.map(pub) };
  });

  // ── Buyer: purchase ─────────────────────────────────────────────────────────
  app.post('/marketplace/products/:id/buy', { preHandler: requireRole() }, async (req, reply) => {
    const p = await db();
    const product = await p.projectProduct.findUnique({ where: { id: req.params.id } });
    if (!product || !product.active) return reply.code(404).send({ error: 'not_found' });
    // Paid products go through Stripe (see /checkout); free ones deliver immediately.
    if (product.priceCents > 0) return reply.code(402).send({ error: 'checkout_required', priceCents: product.priceCents, currency: product.currency });
    // Take the slot BEFORE handing anything over, in one statement the database evaluates
    // against the row it is writing. `sold >= stock` read from a row fetched a moment ago is
    // the same read-then-write that let two webhook deliveries both claim one session: fire
    // N requests at "the first 100 are free" and all N read sold = 99 and all N pass.
    //
    // Raw because the condition compares two COLUMNS, which Prisma's `where` cannot express
    // — writing it as `sold: { lt: product.stock }` would compare against the number this
    // request happened to read, which is the bug rather than the fix.
    const took = await p.$executeRaw`UPDATE "ProjectProduct" SET "sold" = "sold" + 1
      WHERE "id" = ${product.id} AND ("stock" IS NULL OR "sold" < "stock")`;
    if (!took) return reply.code(409).send({ error: 'out_of_stock' });
    let delivery;
    try { delivery = await fulfilProduct(p, product, req.user.uid); }
    catch (e) {
      // Give the slot back — an undelivered claim that still counts against the stock spends
      // somebody else's place on a purchase that never happened.
      await p.projectProduct.update({ where: { id: product.id }, data: { sold: { decrement: 1 } } }).catch(() => {});
      return reply.code(409).send({ error: e.code || 'delivery_failed' });
    }
    // feeCents/netCents are written even at zero. A free purchase with NULL where the split
    // should be is indistinguishable from an old row nobody computed, and a payout report
    // that has to guess which is which is a payout report nobody trusts.
    const purchase = await p.projectProductPurchase.create({ data: { productId: product.id, buyerId: req.user.uid, status: 'paid', priceCents: 0, feeCents: 0, netCents: 0, delivery } });
    return { ok: true, purchase: { id: purchase.id, delivery } };
  });

  // ── Buyer: Stripe checkout for a PAID product (delivery happens in the webhook) ──────────
  app.post('/marketplace/products/:id/checkout', { preHandler: requireRole() }, async (req, reply) => {
    const p = await db();
    const product = await p.projectProduct.findUnique({ where: { id: req.params.id } });
    if (!product || !product.active) return reply.code(404).send({ error: 'not_found' });
    if (product.priceCents <= 0) return reply.code(400).send({ error: 'free_product' }); // use /buy
    if (product.stock != null && product.sold >= product.stock) return reply.code(409).send({ error: 'out_of_stock' });
    // A pool product with no free key left cannot be sold — refuse before taking money.
    if (product.deliveryKind === 'key_pool') {
      const free = await p.projectKey.count({ where: { productId: product.id, claimedAt: null } });
      if (free <= 0) return reply.code(409).send({ error: 'out_of_stock' });
    }
    const sk = await stripe();
    if (!sk) return reply.code(503).send({ error: 'payments_unavailable' });
    const siteUrl = process.env.SITE_URL || 'http://localhost:5176';
    const customer = await ensureCustomer(p, sk, req.user.uid);
    const recurring = product.billing === 'subscription';

    // Where the seller's share goes, decided HERE rather than in the webhook. The webhook
    // sees a paid session and has to know what the charge was actually built with; asking
    // it to re-derive the payee would let a payout account changed in between be applied
    // to a charge that never routed to it.
    const seller = await sellerForProduct(p, product);
    const routed = connectChargeParams(product, seller, await feeForProduct(p, product));
    const md = {
      type: 'marketplace', productId: product.id, userId: req.user.uid,
      // Stripe metadata values are strings; '' means the platform kept it, which is also
      // what every sale before Connect did.
      sellerAccountId: routed ? seller.stripeAccountId : '',
    };

    // A subscription needs a Stripe PRICE, not an inline amount, and the same one every
    // time. Minting a new price per checkout works and makes the Stripe dashboard
    // unreadable: "how many people are on this plan" stops having an answer, for ever.
    let priceId = product.stripePriceId || null;
    if (recurring && !priceId) {
      const months = Math.min(12, Math.max(1, Number(product.intervalMonths) || 1));
      const created = await sk.prices.create({
        currency: product.currency || 'usd',
        unit_amount: product.priceCents,
        recurring: { interval: 'month', interval_count: months },
        product_data: { name: product.name },
      });
      priceId = created.id;
      await p.projectProduct.update({ where: { id: product.id }, data: { stripePriceId: priceId } });
    }

    const session = await sk.checkout.sessions.create({
      mode: recurring ? 'subscription' : 'payment', customer,
      line_items: recurring
        ? [{ quantity: 1, price: priceId }]
        : [{ quantity: 1, price_data: { currency: product.currency || 'usd', unit_amount: product.priceCents, product_data: { name: product.name } } }],
      // Only a one-off session takes invoice_creation; a subscription invoices every cycle
      // by itself, and passing both is a 400 from Stripe.
      ...(recurring ? {} : { invoice_creation: { enabled: true } }),
      metadata: md,
      // Carried onto the SUBSCRIPTION as well, so a renewal months later still knows which
      // product it is for. Session metadata does not survive onto the subscription object.
      // The routed params are merged INTO subscription_data rather than beside it — two keys
      // of the same name and the second silently wins, taking the metadata with it.
      ...(recurring ? { subscription_data: { metadata: md, ...(routed?.subscription_data || {}) } } : {}),
      ...(routed?.payment_intent_data ? { payment_intent_data: routed.payment_intent_data } : {}),
      success_url: `${siteUrl}/dashboard?market=ok`,
      cancel_url: `${siteUrl}/dashboard?market=cancel`,
    });
    return { url: session.url };
  });

  // ── Buyer: my purchases for a project ───────────────────────────────────────
  app.get('/marketplace/my-purchases', { preHandler: requireRole() }, async (req) => {
    const p = await db();
    const rows = await p.projectProductPurchase.findMany({
      where: { buyerId: req.user.uid }, orderBy: { createdAt: 'desc' }, take: 200,
      include: { product: { select: { name: true, projectKey: true, showcaseProjectId: true } } },
    });
    return { purchases: rows.map((r) => ({ id: r.id, name: r.product?.name, status: r.status, delivery: r.delivery, createdAt: r.createdAt })) };
  });

  // ── Product CRUD, scoped to the pages the caller may administer ───────────────────
  //
  // These were all requireRole('ADMIN'), which meant running ONE project's shop required
  // admin of the whole site — and then reached every other project's products, keys and
  // prices. A scoped role can now carry the 'market' right on the pages it covers.

  /** What this caller may do, resolved once per request: site-wide power, plus their grants. */
  async function marketPower(user) {
    const manageAll = hasCap(user, 'manage_projects') || hasCap(user, 'manage_showcase');
    if (manageAll) return { power: { manageAll: true }, grants: null };
    // Both sources, unioned: an individual ProjectPermission row and a market-scoped role.
    const [pg, mg] = await Promise.all([projectGrants(user?.uid), marketRoleGrants(user?.uid)]);
    return {
      power: { manageAll: false },
      grants: {
        // A page grant alone is NOT a shop grant. projectGrants carries the 'pages' right,
        // and "edits the BSM page" has never meant "sets the price of what BSM sells" —
        // reading it that way here would hand the shop to everyone who ever got page access.
        allShowcase: mg.allShowcase,
        showcaseIds: mg.showcaseIds,
        projectKeys: mg.projectKeys,
        _pages: pg,
      },
    };
  }

  /** Load a product and refuse it unless this caller may administer its page. */
  async function productForCaller(p, id, user, reply) {
    const row = await p.projectProduct.findUnique({ where: { id } });
    if (!row) { reply.code(404).send({ error: 'not_found' }); return null; }
    const { power, grants } = await marketPower(user);
    if (!marketScopeAllows(power, grants, row)) { reply.code(403).send({ error: 'forbidden_scope' }); return null; }
    return row;
  }

  app.get('/admin/marketplace/products', { preHandler: requireEditor() }, async (req, reply) => {
    const p = await db();
    const { power, grants } = await marketPower(req.user);
    // Nothing to administer is 403, not an empty list: an empty shop and no access to the
    // shop look identical on screen, and only one of them is worth telling somebody about.
    if (!power.manageAll && !grants.projectKeys.size && !grants.showcaseIds.size && !grants.allShowcase) {
      return reply.code(403).send({ error: 'forbidden_scope' });
    }
    const where = {};
    if (req.query?.projectKey) where.projectKey = String(req.query.projectKey);
    if (req.query?.showcaseProjectId) where.showcaseProjectId = String(req.query.showcaseProjectId);
    // FILTERED, not merely refused when somebody asks for another page. An unfiltered list
    // is every product, price and margin on the site handed to anybody with one grant.
    if (!power.manageAll) {
      where.OR = [
        ...(grants.projectKeys.size ? [{ projectKey: { in: [...grants.projectKeys] } }] : []),
        ...(grants.allShowcase ? [{ showcaseProjectId: { not: null } }]
          : grants.showcaseIds.size ? [{ showcaseProjectId: { in: [...grants.showcaseIds] } }] : []),
      ];
    }
    const rows = await p.projectProduct.findMany({ where, orderBy: { createdAt: 'desc' }, take: 500, include: { _count: { select: { keys: true, purchases: true } } } });
    // Both the default AND the per-project map ride along, so the screen can say which of
    // the three levels a product's margin came from rather than leaving an empty field that
    // reads as "no margin on this one".
    const defaultFeeBp = await marketplaceFeeBp(p);
    const feeByProject = await marketplaceFeeByProject(p);
    return {
      defaultFeeBp, feeByProject,
      products: rows.map((r) => {
        const scope = feeScopeOf(r);
        const own = validBp(r.feePercentBp);
        const forPage = scope ? validBp(feeByProject[scope]) : null;
        return {
          ...r, externalSecret: r.externalSecret ? '••••' : null,
          keyCount: r._count.keys, purchaseCount: r._count.purchases, _count: undefined,
          feeScope: scope,
          effectiveFeeBp: own ?? forPage ?? defaultFeeBp,
          // Which level answered. The screen shows it, because "5%" with no idea whether it
          // came from this product, its page or the site is a number nobody dares change.
          feeFrom: own !== null ? 'product' : forPage !== null ? 'project' : 'site',
        };
      }),
    };
  });

  app.post('/admin/marketplace/products', { preHandler: requireEditor() }, async (req, reply) => {
    const b = productSchema.safeParse(req.body);
    if (!b.success) return reply.code(400).send({ error: 'invalid_input', details: b.error.flatten() });
    if (!b.data.projectKey && !b.data.showcaseProjectId) return reply.code(400).send({ error: 'project_required' });
    // A product sits on ONE page. A row naming two is what the list filter and the per-row
    // scope check disagree about — the filter matches it by either id, the check reads only
    // the first — and that disagreement is the hole above.
    if (b.data.projectKey && b.data.showcaseProjectId) return reply.code(400).send({ error: 'one_page_only' });
    const p = await db();
    const { power, grants } = await marketPower(req.user);
    if (!marketScopeAllows(power, grants, b.data)) return reply.code(403).send({ error: 'forbidden_scope' });
    const created = await p.projectProduct.create({ data: stripPrivileged(b.data, req.user) });
    return { ok: true, product: created };
  });

  app.patch('/admin/marketplace/products/:id', { preHandler: requireEditor() }, async (req, reply) => {
    const b = productSchema.partial().safeParse(req.body);
    if (!b.success) return reply.code(400).send({ error: 'invalid_input' });
    const p = await db();
    const exists = await productForCaller(p, req.params.id, req.user, reply);
    if (!exists) return;
    // MOVING a product is checked on the destination too. Without this, a grantee edits a
    // product they hold and sets projectKey to a page they do not — and it is now on that
    // page, under its name, with its margin.
    if (b.data.projectKey !== undefined || b.data.showcaseProjectId !== undefined) {
      const dest = {
        projectKey: b.data.projectKey !== undefined ? b.data.projectKey : exists.projectKey,
        showcaseProjectId: b.data.showcaseProjectId !== undefined ? b.data.showcaseProjectId : exists.showcaseProjectId,
      };
      if (dest.projectKey && dest.showcaseProjectId) return reply.code(400).send({ error: 'one_page_only' });
      const { power, grants } = await marketPower(req.user);
      if (!marketScopeAllows(power, grants, dest)) return reply.code(403).send({ error: 'forbidden_scope' });
    }
    // A price or interval change invalidates the cached Stripe price: leaving it would keep
    // charging the old amount on every new subscription, silently, for ever.
    const data = stripPrivileged(b.data, req.user);
    const repriced = (data.priceCents != null && data.priceCents !== exists.priceCents)
      || (data.currency != null && data.currency !== exists.currency)
      || (data.intervalMonths != null && data.intervalMonths !== exists.intervalMonths)
      || (data.billing != null && data.billing !== exists.billing);
    if (repriced) data.stripePriceId = null;
    const updated = await p.projectProduct.update({ where: { id: req.params.id }, data });
    return { ok: true, product: updated };
  });

  app.delete('/admin/marketplace/products/:id', { preHandler: requireEditor() }, async (req, reply) => {
    const p = await db();
    const row = await productForCaller(p, req.params.id, req.user, reply);
    if (!row) return;
    await p.projectProduct.delete({ where: { id: req.params.id } }).catch(() => {});
    await logAudit(p, req.user.uid, 'marketplace.product_deleted', row.name, clientIp(req));
    return { ok: true };
  });

  // ── Admin: add keys to a product's pool ─────────────────────────────────────
  // ── Buyer: download a file they bought ───────────────────────────────────────
  //
  // The signed URL is minted HERE, per request, against a purchase that exists — not stored on
  // the product and not handed out at purchase time. A link that never expires is the thing
  // this delivery kind exists to avoid: pasted into `content` it would be forwardable for ever.
  app.get('/marketplace/purchases/:id/download', { preHandler: requireRole() }, async (req, reply) => {
    const p = await db();
    const purchase = await p.projectProductPurchase.findUnique({ where: { id: req.params.id }, include: { product: true } });
    if (!purchase || purchase.buyerId !== req.user.uid) return reply.code(404).send({ error: 'not_found' });
    // 'paid' is a one-off (and a free claim). A SUBSCRIPTION is created 'active' by the
    // webhook and becomes 'ended' when it lapses — and nothing couples deliveryKind to
    // billing, so a `file` product sold monthly is an ordinary thing to build. Checking only
    // for 'paid' locked the paying customer out of the file for the whole life of their
    // subscription, and answered 'not_paid' to somebody who had.
    if (!mayDownload(purchase.status)) {
      return reply.code(409).send({ error: purchase.status === 'ended' ? 'subscription_ended' : 'not_paid' });
    }
    // The key comes from the PURCHASE, so replacing the product's file later does not silently
    // hand an old buyer a different file than the one they paid for.
    const key = purchase.delivery?.fileKey || purchase.product?.fileKey;
    if (!key) return reply.code(409).send({ error: 'no_file' });
    const url = await presignGet(key, DOWNLOAD_TTL).catch(() => null);
    if (!url) return reply.code(503).send({ error: 'storage_unavailable' });
    return { url, expiresInSec: DOWNLOAD_TTL, fileName: purchase.delivery?.fileName || purchase.product?.fileName || 'download' };
  });

  // ── Admin: attach the file a `file` product hands over ───────────────────────
  app.post('/admin/marketplace/products/:id/file', { preHandler: requireEditor(), bodyLimit: 64 * 1024 * 1024 }, async (req, reply) => {
    const b = z.object({
      fileName: z.string().min(1).max(200),
      contentType: z.string().max(100).optional().default('application/octet-stream'),
      data: z.string().min(1), // base64
    }).safeParse(req.body);
    if (!b.success) return reply.code(400).send({ error: 'invalid_input' });
    const p = await db();
    const product = await productForCaller(p, req.params.id, req.user, reply);
    if (!product) return;
    let buf;
    try { buf = Buffer.from(b.data.data, 'base64'); } catch { return reply.code(400).send({ error: 'bad_file' }); }
    // Checked BEFORE the object is written, and against the total minus whatever this product
    // already holds — replacing a 40 MB file with a 41 MB one must be judged on the one
    // megabyte it adds, not on the forty-one it would be if the old file were staying.
    const store = await marketplaceStorage(p);
    const delta = buf.length - Number(product.fileBytes || 0);
    if (store.capBytes > 0 && delta > 0 && store.usedBytes + delta > store.capBytes) {
      return reply.code(413).send({
        error: 'marketplace_storage_full',
        usedBytes: store.usedBytes, capBytes: store.capBytes, needBytes: delta,
      });
    }
    // The name is sanitised for the KEY only; the original is kept for the download's filename,
    // so a buyer gets back what the admin uploaded rather than a mangled version of it.
    const safe = String(b.data.fileName).replace(/[^\w.-]+/g, '_').slice(0, 80) || 'file';
    const key = `${FILE_PREFIX}/${product.id}/${crypto.randomUUID().replace(/-/g, '').slice(0, 12)}-${safe}`;
    try { await putObject(key, buf, b.data.contentType); }
    catch (e) { req.log.warn({ e: String(e) }, 'marketplace file store failed'); return reply.code(503).send({ error: 'storage_unavailable' }); }
    // The previous file is removed only after the new one is safely stored — the other order
    // loses the old file when the upload fails.
    if (product.fileKey && product.fileKey !== key) await deleteObject(product.fileKey).catch(() => {});
    const row = await p.projectProduct.update({ where: { id: product.id }, data: { fileKey: key, fileName: b.data.fileName.slice(0, 200), fileBytes: buf.length } });
    return { ok: true, fileName: row.fileName, bytes: buf.length, storage: await marketplaceStorage(p) };
  });

  /**
   * Mint keys into the pool, here, instead of pasting them in from somewhere else.
   *
   * `key_pool` could only be filled by hand: generate codes in another tool, paste them, and
   * hope nobody kept a copy of the list. `key_license` mints on demand but stores nothing —
   * which means no stock to show, no way to see what was handed out, and no way to revoke one.
   *
   * This is the middle both were missing: BCWEB generates them, keeps them, and hands them out
   * one at a time through the same race-safe claim the pool already uses. The alphabet drops
   * the characters people misread aloud (0/O, 1/I/L), which matters for something read off a
   * screen and typed into a game.
   *
   * Uniqueness is enforced by asking the database what it already has rather than by trusting
   * the odds — 31^20 is a comfortable space, but "comfortable" is not the same as "checked",
   * and a duplicate would hand two buyers the same key.
   */
  app.post('/admin/marketplace/products/:id/keys/mint', { preHandler: requireEditor() }, async (req, reply) => {
    const b = z.object({
      count: z.number().int().min(1).max(1000),
      prefix: z.string().max(12).regex(/^[A-Z0-9-]*$/).optional().default(''),
    }).safeParse(req.body || {});
    if (!b.success) return reply.code(400).send({ error: 'invalid_input' });
    const p = await db();
    const product = await productForCaller(p, req.params.id, req.user, reply);
    if (!product) return;

    const A = 'ABCDEFGHJKMNPQRSTUVWXYZ23456789';
    const group = () => Array.from({ length: 5 }, () => A[crypto.randomInt(A.length)]).join('');
    const make = () => `${b.data.prefix ? `${b.data.prefix}-` : ''}${group()}-${group()}-${group()}-${group()}`;

    const existing = new Set((await p.projectKey.findMany({ where: { productId: product.id }, select: { code: true } })).map((k) => k.code));
    const fresh = new Set();
    // Bounded: a pathological run of collisions must not spin. In practice the loop runs
    // `count` times.
    for (let i = 0; i < b.data.count * 20 && fresh.size < b.data.count; i++) {
      const c = make();
      if (!existing.has(c) && !fresh.has(c)) fresh.add(c);
    }
    if (fresh.size < b.data.count) return reply.code(500).send({ error: 'could_not_mint' });

    await p.projectKey.createMany({ data: [...fresh].map((code) => ({ productId: product.id, code })) });
    const [total, free] = await Promise.all([
      p.projectKey.count({ where: { productId: product.id } }),
      p.projectKey.count({ where: { productId: product.id, claimedAt: null } }),
    ]);
    await logAudit(p, req.user.uid, 'marketplace.keys_mint', `${product.name}: +${fresh.size}`, clientIp(req));
    return { ok: true, minted: fresh.size, total, free };
  });

  // ── Payouts: who gets the money for a page's sales ────────────────────────────────
  //
  // SUPERADMIN throughout, and not ADMIN. The margin is already SUPERADMIN-only because it
  // decides how much of somebody else's sale we keep; this is the same question with a
  // bigger answer, and an ADMIN who could point a project's revenue at an account they
  // control would be one request away from taking it.

  /** Every payee on file, with what Stripe last said about it. */
  app.get('/admin/marketplace/sellers', { preHandler: requireRole('SUPERADMIN') }, async () => {
    const p = await db();
    const rows = await p.marketplaceSeller.findMany({ orderBy: { scope: 'asc' } });
    return { sellers: rows };
  });

  /**
   * Start (or resume) onboarding for one page, and hand back the Stripe-hosted link.
   *
   * The account is created ONCE and reused: account links expire in minutes and are
   * single-use, so "connect" is pressed again and again during onboarding, and minting a
   * new account each time would leave a trail of half-finished ones with our metadata on
   * them and no way to tell which is real.
   */
  app.post('/admin/marketplace/sellers/onboard', { preHandler: requireRole('SUPERADMIN') }, async (req, reply) => {
    const b = z.object({ scope: z.string().min(3).max(120), country: z.string().length(2).optional() }).safeParse(req.body);
    if (!b.success) return reply.code(400).send({ error: 'invalid_input' });
    const scope = b.data.scope;
    if (!/^(project|showcase):[A-Za-z0-9_-]{1,80}$/.test(scope)) return reply.code(400).send({ error: 'bad_scope' });
    const p = await db();
    const sk = await stripe();
    if (!sk) return reply.code(503).send({ error: 'payments_unavailable' });

    let row = await p.marketplaceSeller.findUnique({ where: { scope } });
    if (!row) {
      const acct = await sk.accounts.create({
        type: 'express',
        ...(b.data.country ? { country: b.data.country } : {}),
        // Destination charges: the platform owns the customer, the price and the dispute,
        // so the platform pays the Stripe fee and handles the loss. Handing `losses` to the
        // seller would mean a chargeback we lose is deducted from somebody who never spoke
        // to the buyer.
        capabilities: { transfers: { requested: true } },
        metadata: { scope, connectedBy: req.user.uid },
      });
      row = await p.marketplaceSeller.create({ data: {
        scope, stripeAccountId: acct.id, connectedById: req.user.uid, ...sellerMirror(acct),
      } });
      await logAudit(p, req.user.uid, 'marketplace.seller_created', `${scope} -> ${acct.id}`, clientIp(req));
    }

    const siteUrl = process.env.SITE_URL || 'http://localhost:5176';
    const link = await sk.accountLinks.create({
      account: row.stripeAccountId,
      type: 'account_onboarding',
      // Both required. `refresh_url` is where Stripe sends somebody whose link expired
      // mid-form, and it has to lead back to a page that can mint a new one — not to the
      // form itself, which would be a dead end for the one person actually onboarding.
      refresh_url: `${siteUrl}/admin?tab=marketplace&connect=refresh&scope=${encodeURIComponent(scope)}`,
      return_url: `${siteUrl}/admin?tab=marketplace&connect=done&scope=${encodeURIComponent(scope)}`,
    });
    return { url: link.url, accountId: row.stripeAccountId };
  });

  /**
   * Pull this account's state from Stripe now.
   *
   * The webhook is the normal path and this is the manual one, for the case the webhook is
   * the thing that is broken — an unconfigured endpoint, a secret rotated, a delivery that
   * failed while somebody was onboarding. Without it the only way to correct a stale mirror
   * is to make Stripe emit another event.
   */
  app.post('/admin/marketplace/sellers/refresh', { preHandler: requireRole('SUPERADMIN') }, async (req, reply) => {
    const b = z.object({ scope: z.string().min(3).max(120) }).safeParse(req.body);
    if (!b.success) return reply.code(400).send({ error: 'invalid_input' });
    const p = await db();
    const row = await p.marketplaceSeller.findUnique({ where: { scope: b.data.scope } });
    if (!row) return reply.code(404).send({ error: 'not_found' });
    const sk = await stripe();
    if (!sk) return reply.code(503).send({ error: 'payments_unavailable' });
    const acct = await sk.accounts.retrieve(row.stripeAccountId);
    const updated = await p.marketplaceSeller.update({ where: { id: row.id }, data: sellerMirror(acct) });
    return { seller: updated };
  });

  /**
   * Stop routing this page's sales to that account.
   *
   * Detaches OUR row; the Stripe account is untouched and keeps whatever it has already been
   * paid. Deleting the account here would orphan transfers that have already happened and
   * are still settling, and it is not ours to delete.
   */
  app.delete('/admin/marketplace/sellers', { preHandler: requireRole('SUPERADMIN') }, async (req, reply) => {
    const scope = String(req.query?.scope || '');
    const p = await db();
    const row = await p.marketplaceSeller.findUnique({ where: { scope } });
    if (!row) return reply.code(404).send({ error: 'not_found' });
    await p.marketplaceSeller.delete({ where: { id: row.id } });
    await logAudit(p, req.user.uid, 'marketplace.seller_detached', `${scope} (${row.stripeAccountId})`, clientIp(req));
    return { ok: true };
  });

  /** How full the marketplace's share of the disk is. Read-only; the cap is a hosting setting. */
  app.get('/admin/marketplace/storage', { preHandler: requireRole('ADMIN') }, async () => marketplaceStorage(await db()));

  app.post('/admin/marketplace/products/:id/keys', { preHandler: requireEditor() }, async (req, reply) => {
    const codes = z.object({ codes: z.array(z.string().min(1).max(400)).max(5000) }).safeParse(req.body);
    if (!codes.success) return reply.code(400).send({ error: 'invalid_input' });
    const p = await db();
    const product = await productForCaller(p, req.params.id, req.user, reply);
    if (!product) return;
    const clean = [...new Set(codes.data.codes.map((c) => c.trim()).filter(Boolean))];
    if (clean.length) await p.projectKey.createMany({ data: clean.map((code) => ({ productId: product.id, code })) });
    const [total, free] = await Promise.all([
      p.projectKey.count({ where: { productId: product.id } }),
      p.projectKey.count({ where: { productId: product.id, claimedAt: null } }),
    ]);
    return { ok: true, added: clean.length, total, free };
  });
}
