// Per-project marketplace (K). A project lists products; a purchase is fulfilled by handing over
// a key (a fixed one, one drawn from a pool, or — later — one generated by an external system),
// some revealed content, or a Discord role. Phase 1: product CRUD, a key pool, and delivery for
// free products (static / pool / content / role). Paid products return `checkout_required` — the
// Stripe one-time flow and the external-key webhook are Phase 2.
import { z } from 'zod';
import crypto from 'node:crypto';
import { db, requireRole } from '../lib/lib.mjs';
import { stripe, ensureCustomer } from './hosting.mjs';

const DELIVERY_KINDS = ['key_static', 'key_pool', 'key_external', 'content', 'role'];

const productSchema = z.object({
  projectKey: z.string().max(60).nullish(),
  showcaseProjectId: z.string().max(60).nullish(),
  name: z.string().min(1).max(120),
  description: z.string().max(2000).optional().default(''),
  priceCents: z.number().int().min(0).max(10_000_00).optional().default(0),
  currency: z.string().max(8).optional().default('usd'),
  active: z.boolean().optional().default(true),
  deliveryKind: z.enum(DELIVERY_KINDS).optional().default('content'),
  staticKey: z.string().max(400).nullish(),
  content: z.string().max(4000).nullish(),
  roleId: z.string().max(32).nullish(),
  externalUrl: z.string().url().max(400).nullish(),
  externalSecret: z.string().max(200).nullish(),
  stock: z.number().int().min(0).max(1_000_000).nullish(),
});

// What a buyer is allowed to see about a product — never the static key, the pool, the external
// secret, or how many are left beyond "in stock or not".
const pub = (pr) => ({
  id: pr.id, name: pr.name, description: pr.description, priceCents: pr.priceCents, currency: pr.currency,
  deliveryKind: pr.deliveryKind, inStock: pr.stock == null || pr.stock > pr.sold,
});

// Ask an external key generator for a code. The admin sets externalUrl + externalSecret; we POST
// a signed body and expect { key } back. Signed with HMAC-SHA256 so the external system can trust
// the request came from us; timed out so a dead endpoint never hangs a purchase.
async function externalKey(product, buyerId) {
  const body = JSON.stringify({ productId: product.id, buyerId, name: product.name, ts: Date.now() });
  const sig = product.externalSecret ? crypto.createHmac('sha256', product.externalSecret).update(body).digest('hex') : '';
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), 10_000);
  try {
    const r = await fetch(product.externalUrl, { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-BC-Signature': sig }, body, signal: ctrl.signal });
    if (!r.ok) { const e = new Error('external_failed'); e.code = 'external_failed'; throw e; }
    const j = await r.json().catch(() => ({}));
    const key = String(j.key || j.code || '').trim();
    if (!key) { const e = new Error('external_no_key'); e.code = 'external_no_key'; throw e; }
    return { key, external: true };
  } catch (e) {
    if (e.code) throw e;
    const err = new Error('external_failed'); err.code = 'external_failed'; throw err;
  } finally { clearTimeout(timer); }
}

// Fulfil a purchase: returns the delivery payload, or throws { code } when it cannot. Exported so
// the Stripe webhook can deliver a paid purchase the same way the free path does.
export async function fulfilProduct(p, product, buyerId) {
  switch (product.deliveryKind) {
    case 'content': return { content: product.content || '' };
    case 'role': return { role: product.roleId || '' };
    case 'key_static': return { key: product.staticKey || '' };
    case 'key_pool': {
      // Claim one unclaimed pool key: pick the oldest free key, mark it. updateMany with a
      // claimedAt:null guard makes the claim race-safe (a second buyer can't take the same key).
      for (let attempt = 0; attempt < 5; attempt++) {
        const free = await p.projectKey.findFirst({ where: { productId: product.id, claimedAt: null }, orderBy: { createdAt: 'asc' } });
        if (!free) { const e = new Error('out_of_stock'); e.code = 'out_of_stock'; throw e; }
        const claimed = await p.projectKey.updateMany({ where: { id: free.id, claimedAt: null }, data: { claimedById: buyerId, claimedAt: new Date() } });
        if (claimed.count === 1) return { key: free.code };
      }
      const e = new Error('out_of_stock'); e.code = 'out_of_stock'; throw e;
    }
    case 'key_external': return externalKey(product, buyerId);
    default: return {};
  }
}

export default async function marketplaceRoutes(app) {
  // ── Public: a project's live products ──────────────────────────────────────
  app.get('/marketplace/products', async (req) => {
    const p = await db();
    const { projectKey, showcaseProjectId } = req.query || {};
    const where = { active: true };
    if (projectKey) where.projectKey = String(projectKey);
    else if (showcaseProjectId) where.showcaseProjectId = String(showcaseProjectId);
    else return { products: [] };
    const rows = await p.projectProduct.findMany({ where, orderBy: { createdAt: 'desc' }, take: 200 });
    return { products: rows.map(pub) };
  });

  // ── Buyer: purchase ─────────────────────────────────────────────────────────
  app.post('/marketplace/products/:id/buy', { preHandler: requireRole() }, async (req, reply) => {
    const p = await db();
    const product = await p.projectProduct.findUnique({ where: { id: req.params.id } });
    if (!product || !product.active) return reply.code(404).send({ error: 'not_found' });
    if (product.stock != null && product.sold >= product.stock) return reply.code(409).send({ error: 'out_of_stock' });
    // Paid products go through Stripe (see /checkout); free ones deliver immediately.
    if (product.priceCents > 0) return reply.code(402).send({ error: 'checkout_required', priceCents: product.priceCents, currency: product.currency });
    let delivery;
    try { delivery = await fulfilProduct(p, product, req.user.uid); }
    catch (e) { return reply.code(409).send({ error: e.code || 'delivery_failed' }); }
    const purchase = await p.projectProductPurchase.create({ data: { productId: product.id, buyerId: req.user.uid, status: 'paid', priceCents: 0, delivery } });
    await p.projectProduct.update({ where: { id: product.id }, data: { sold: { increment: 1 } } });
    return { ok: true, purchase: { id: purchase.id, delivery } };
  });

  // ── Buyer: Stripe checkout for a PAID product (delivery happens in the webhook) ──────────
  app.post('/marketplace/products/:id/checkout', { preHandler: requireRole() }, async (req, reply) => {
    const p = await db();
    const product = await p.projectProduct.findUnique({ where: { id: req.params.id } });
    if (!product || !product.active) return reply.code(404).send({ error: 'not_found' });
    if (product.priceCents <= 0) return reply.code(400).send({ error: 'free_product' }); // use /buy
    if (product.stock != null && product.sold >= product.stock) return reply.code(409).send({ error: 'out_of_stock' });
    // A pool product with no free key left cannot be sold — refuse before taking money.
    if (product.deliveryKind === 'key_pool') {
      const free = await p.projectKey.count({ where: { productId: product.id, claimedAt: null } });
      if (free <= 0) return reply.code(409).send({ error: 'out_of_stock' });
    }
    const sk = await stripe();
    if (!sk) return reply.code(503).send({ error: 'payments_unavailable' });
    const siteUrl = process.env.SITE_URL || 'http://localhost:5176';
    const customer = await ensureCustomer(p, sk, req.user.uid);
    const md = { type: 'marketplace', productId: product.id, userId: req.user.uid };
    const session = await sk.checkout.sessions.create({
      mode: 'payment', customer,
      line_items: [{ quantity: 1, price_data: { currency: product.currency || 'usd', unit_amount: product.priceCents, product_data: { name: product.name } } }],
      invoice_creation: { enabled: true },
      metadata: md,
      success_url: `${siteUrl}/dashboard?market=ok`,
      cancel_url: `${siteUrl}/dashboard?market=cancel`,
    });
    return { url: session.url };
  });

  // ── Buyer: my purchases for a project ───────────────────────────────────────
  app.get('/marketplace/my-purchases', { preHandler: requireRole() }, async (req) => {
    const p = await db();
    const rows = await p.projectProductPurchase.findMany({
      where: { buyerId: req.user.uid }, orderBy: { createdAt: 'desc' }, take: 200,
      include: { product: { select: { name: true, projectKey: true, showcaseProjectId: true } } },
    });
    return { purchases: rows.map((r) => ({ id: r.id, name: r.product?.name, status: r.status, delivery: r.delivery, createdAt: r.createdAt })) };
  });

  // ── Admin: product CRUD (owner-scoping is a Phase-2 refinement) ──────────────
  app.get('/admin/marketplace/products', { preHandler: requireRole('ADMIN') }, async (req) => {
    const p = await db();
    const where = {};
    if (req.query?.projectKey) where.projectKey = String(req.query.projectKey);
    if (req.query?.showcaseProjectId) where.showcaseProjectId = String(req.query.showcaseProjectId);
    const rows = await p.projectProduct.findMany({ where, orderBy: { createdAt: 'desc' }, take: 500, include: { _count: { select: { keys: true, purchases: true } } } });
    return { products: rows.map((r) => ({ ...r, externalSecret: r.externalSecret ? '••••' : null, keyCount: r._count.keys, purchaseCount: r._count.purchases, _count: undefined })) };
  });

  app.post('/admin/marketplace/products', { preHandler: requireRole('ADMIN') }, async (req, reply) => {
    const b = productSchema.safeParse(req.body);
    if (!b.success) return reply.code(400).send({ error: 'invalid_input', details: b.error.flatten() });
    if (!b.data.projectKey && !b.data.showcaseProjectId) return reply.code(400).send({ error: 'project_required' });
    const p = await db();
    const created = await p.projectProduct.create({ data: b.data });
    return { ok: true, product: created };
  });

  app.patch('/admin/marketplace/products/:id', { preHandler: requireRole('ADMIN') }, async (req, reply) => {
    const b = productSchema.partial().safeParse(req.body);
    if (!b.success) return reply.code(400).send({ error: 'invalid_input' });
    const p = await db();
    const exists = await p.projectProduct.findUnique({ where: { id: req.params.id } });
    if (!exists) return reply.code(404).send({ error: 'not_found' });
    const updated = await p.projectProduct.update({ where: { id: req.params.id }, data: b.data });
    return { ok: true, product: updated };
  });

  app.delete('/admin/marketplace/products/:id', { preHandler: requireRole('ADMIN') }, async (req) => {
    const p = await db();
    await p.projectProduct.delete({ where: { id: req.params.id } }).catch(() => {});
    return { ok: true };
  });

  // ── Admin: add keys to a product's pool ─────────────────────────────────────
  app.post('/admin/marketplace/products/:id/keys', { preHandler: requireRole('ADMIN') }, async (req, reply) => {
    const codes = z.object({ codes: z.array(z.string().min(1).max(400)).max(5000) }).safeParse(req.body);
    if (!codes.success) return reply.code(400).send({ error: 'invalid_input' });
    const p = await db();
    const product = await p.projectProduct.findUnique({ where: { id: req.params.id } });
    if (!product) return reply.code(404).send({ error: 'not_found' });
    const clean = [...new Set(codes.data.codes.map((c) => c.trim()).filter(Boolean))];
    if (clean.length) await p.projectKey.createMany({ data: clean.map((code) => ({ productId: product.id, code })) });
    const [total, free] = await Promise.all([
      p.projectKey.count({ where: { productId: product.id } }),
      p.projectKey.count({ where: { productId: product.id, claimedAt: null } }),
    ]);
    return { ok: true, added: clean.length, total, free };
  });
}
