// Per-project marketplace (K). A project lists products; a purchase is fulfilled by handing over
// a key (a fixed one, one drawn from a pool, or — later — one generated by an external system),
// some revealed content, or a Discord role. Phase 1: product CRUD, a key pool, and delivery for
// free products (static / pool / content / role). Paid products return `checkout_required` — the
// Stripe one-time flow and the external-key webhook are Phase 2.
import { z } from 'zod';
import crypto from 'node:crypto';
import { db, requireRole, logAudit, clientIp } from '../lib/lib.mjs';
import { presignGet, putObject, deleteObject } from '../lib/storage.mjs';
import { sendMail, mailShell, emailEnabled } from '../lib/mail.mjs';
import { stripe, ensureCustomer } from './hosting.mjs';

// What a product HANDS OVER. The first five were the whole of it, and between them they
// could not sell the most ordinary thing a project sells — a file. The workaround was to paste
// a download link into `content`, which makes it a public URL: it is in the buyer's purchase
// row, and in anybody else's the moment they share it, for ever.
//
//   key_static    one key, the same for everyone
//   key_pool      one key drawn from a finite list, claimed race-safely
//   key_license   a UNIQUE key minted per buyer — infinite supply, traceable to the purchase
//   key_external  a key fetched from the project's own system
//   content       revealed text (a code, instructions, a coupon)
//   file          a file held in the platform's own storage, handed over as a SHORT-LIVED
//                 signed URL re-issued per buyer rather than a link that never expires
//   link          a plain URL, as a real button rather than a paragraph
//   role          a Discord role
const DELIVERY_KINDS = ['key_static', 'key_pool', 'key_license', 'key_external', 'content', 'file', 'link', 'role'];
/** Where a product's file lives. Private: nothing under this prefix is publicly served. */
const FILE_PREFIX = 'marketplace';
/** How long a download link stays good. Long enough to click, short enough not to be a
 *  distributable URL — the reason the file kind exists rather than a pasted link. */
const DOWNLOAD_TTL = 600;

/**
 * What the marketplace is allowed to weigh, in MB, and what it weighs now.
 *
 * Every other place a byte can land on this platform is metered — hosted repos have a quota,
 * catalogues draw from a pool, Discord activity has a cap, analytics has a retention. Product
 * files had nothing: a 64 MB body limit per request and no ceiling above it, on the same disk
 * the hosting page sells by the gigabyte. Enough products and the marketplace quietly eats the
 * capacity somebody paid for.
 *
 * One global ceiling rather than a per-project quota, because a product is not attached to a
 * hosting pool — it hangs off a project key — and inventing a second, parallel notion of
 * "this project's storage" is how two numbers that should agree stop agreeing.
 */
const DEFAULT_STORAGE_MB = 2048;
export async function marketplaceStorage(p) {
  const row = await p.adminSetting.findUnique({ where: { key: 'marketplace.storageMB' } }).catch(() => null);
  const capMB = Math.max(0, Number(row?.value ?? DEFAULT_STORAGE_MB) || 0);
  const agg = await p.projectProduct.aggregate({ _sum: { fileBytes: true }, _count: { fileKey: true } });
  const usedBytes = Number(agg._sum.fileBytes || 0);
  return {
    capMB, capBytes: capMB * 1024 * 1024, usedBytes, files: agg._count.fileKey || 0,
    freeBytes: Math.max(0, capMB * 1024 * 1024 - usedBytes),
  };
}

const productSchema = z.object({
  projectKey: z.string().max(60).nullish(),
  showcaseProjectId: z.string().max(60).nullish(),
  name: z.string().min(1).max(120),
  description: z.string().max(2000).optional().default(''),
  priceCents: z.number().int().min(0).max(10_000_00).optional().default(0),
  currency: z.string().max(8).optional().default('usd'),
  active: z.boolean().optional().default(true),
  deliveryKind: z.enum(DELIVERY_KINDS).optional().default('content'),
  staticKey: z.string().max(400).nullish(),
  content: z.string().max(4000).nullish(),
  roleId: z.string().max(32).nullish(),
  fileKey: z.string().max(300).nullish(),
  fileName: z.string().max(200).nullish(),
  linkUrl: z.string().url().max(600).nullish(),
  externalUrl: z.string().url().max(400).nullish(),
  externalSecret: z.string().max(200).nullish(),
  stock: z.number().int().min(0).max(1_000_000).nullish(),
});

// What a buyer is allowed to see about a product — never the static key, the pool, the external
// secret, or how many are left beyond "in stock or not".
const pub = (pr) => ({
  id: pr.id, name: pr.name, description: pr.description, priceCents: pr.priceCents, currency: pr.currency,
  deliveryKind: pr.deliveryKind, inStock: pr.stock == null || pr.stock > pr.sold,
});

// Ask an external key generator for a code. The admin sets externalUrl + externalSecret; we POST
// a signed body and expect { key } back. Signed with HMAC-SHA256 so the external system can trust
// the request came from us; timed out so a dead endpoint never hangs a purchase.
async function externalKey(product, buyerId) {
  const body = JSON.stringify({ productId: product.id, buyerId, name: product.name, ts: Date.now() });
  const sig = product.externalSecret ? crypto.createHmac('sha256', product.externalSecret).update(body).digest('hex') : '';
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), 10_000);
  try {
    const r = await fetch(product.externalUrl, { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-BC-Signature': sig }, body, signal: ctrl.signal });
    if (!r.ok) { const e = new Error('external_failed'); e.code = 'external_failed'; throw e; }
    const j = await r.json().catch(() => ({}));
    const key = String(j.key || j.code || '').trim();
    if (!key) { const e = new Error('external_no_key'); e.code = 'external_no_key'; throw e; }
    return { key, external: true };
  } catch (e) {
    if (e.code) throw e;
    const err = new Error('external_failed'); err.code = 'external_failed'; throw err;
  } finally { clearTimeout(timer); }
}

// Fulfil a purchase: returns the delivery payload, or throws { code } when it cannot. Exported so
// the Stripe webhook can deliver a paid purchase the same way the free path does.
export async function fulfilProduct(p, product, buyerId) {
  switch (product.deliveryKind) {
    case 'content': return { content: product.content || '' };
    case 'role': return { role: product.roleId || '' };
    case 'key_static': return { key: product.staticKey || '' };
    case 'key_pool': {
      // Claim one unclaimed pool key: pick the oldest free key, mark it. updateMany with a
      // claimedAt:null guard makes the claim race-safe (a second buyer can't take the same key).
      for (let attempt = 0; attempt < 5; attempt++) {
        const free = await p.projectKey.findFirst({ where: { productId: product.id, claimedAt: null }, orderBy: { createdAt: 'asc' } });
        if (!free) { const e = new Error('out_of_stock'); e.code = 'out_of_stock'; throw e; }
        const claimed = await p.projectKey.updateMany({ where: { id: free.id, claimedAt: null }, data: { claimedById: buyerId, claimedAt: new Date() } });
        if (claimed.count === 1) return { key: free.code };
      }
      const e = new Error('out_of_stock'); e.code = 'out_of_stock'; throw e;
    }
    case 'key_license': {
      // A key nobody else has, minted here. Unlike a static key it cannot be shared back into
      // the wild without being traceable, and unlike a pool it never runs out. The alphabet
      // drops the characters people misread out loud (0/O, 1/I/L).
      const A = 'ABCDEFGHJKMNPQRSTUVWXYZ23456789';
      const part = () => Array.from({ length: 5 }, () => A[crypto.randomInt(A.length)]).join('');
      return { key: `${part()}-${part()}-${part()}-${part()}`, licensed: true };
    }
    case 'file':
      // The KEY is stored, never the URL: a signed link is minted per download and expires, so
      // what sits in the purchase row cannot be forwarded to somebody who did not buy it.
      if (!product.fileKey) { const e = new Error('no_file'); e.code = 'no_file'; throw e; }
      return { fileKey: product.fileKey, fileName: product.fileName || 'download' };
    case 'link': return { url: product.linkUrl || '' };
    case 'key_external': return externalKey(product, buyerId);
    default: return {};
  }
}

export default async function marketplaceRoutes(app) {
  // ── Public: a project's live products ──────────────────────────────────────
  app.get('/marketplace/products', async (req) => {
    const p = await db();
    const { projectKey, showcaseProjectId } = req.query || {};
    const where = { active: true };
    if (projectKey) where.projectKey = String(projectKey);
    else if (showcaseProjectId) where.showcaseProjectId = String(showcaseProjectId);
    else return { products: [] };
    const rows = await p.projectProduct.findMany({ where, orderBy: { createdAt: 'desc' }, take: 200 });
    return { products: rows.map(pub) };
  });

  // ── Buyer: purchase ─────────────────────────────────────────────────────────
  app.post('/marketplace/products/:id/buy', { preHandler: requireRole() }, async (req, reply) => {
    const p = await db();
    const product = await p.projectProduct.findUnique({ where: { id: req.params.id } });
    if (!product || !product.active) return reply.code(404).send({ error: 'not_found' });
    if (product.stock != null && product.sold >= product.stock) return reply.code(409).send({ error: 'out_of_stock' });
    // Paid products go through Stripe (see /checkout); free ones deliver immediately.
    if (product.priceCents > 0) return reply.code(402).send({ error: 'checkout_required', priceCents: product.priceCents, currency: product.currency });
    let delivery;
    try { delivery = await fulfilProduct(p, product, req.user.uid); }
    catch (e) { return reply.code(409).send({ error: e.code || 'delivery_failed' }); }
    const purchase = await p.projectProductPurchase.create({ data: { productId: product.id, buyerId: req.user.uid, status: 'paid', priceCents: 0, delivery } });
    await p.projectProduct.update({ where: { id: product.id }, data: { sold: { increment: 1 } } });
    return { ok: true, purchase: { id: purchase.id, delivery } };
  });

  // ── Buyer: Stripe checkout for a PAID product (delivery happens in the webhook) ──────────
  app.post('/marketplace/products/:id/checkout', { preHandler: requireRole() }, async (req, reply) => {
    const p = await db();
    const product = await p.projectProduct.findUnique({ where: { id: req.params.id } });
    if (!product || !product.active) return reply.code(404).send({ error: 'not_found' });
    if (product.priceCents <= 0) return reply.code(400).send({ error: 'free_product' }); // use /buy
    if (product.stock != null && product.sold >= product.stock) return reply.code(409).send({ error: 'out_of_stock' });
    // A pool product with no free key left cannot be sold — refuse before taking money.
    if (product.deliveryKind === 'key_pool') {
      const free = await p.projectKey.count({ where: { productId: product.id, claimedAt: null } });
      if (free <= 0) return reply.code(409).send({ error: 'out_of_stock' });
    }
    const sk = await stripe();
    if (!sk) return reply.code(503).send({ error: 'payments_unavailable' });
    const siteUrl = process.env.SITE_URL || 'http://localhost:5176';
    const customer = await ensureCustomer(p, sk, req.user.uid);
    const md = { type: 'marketplace', productId: product.id, userId: req.user.uid };
    const session = await sk.checkout.sessions.create({
      mode: 'payment', customer,
      line_items: [{ quantity: 1, price_data: { currency: product.currency || 'usd', unit_amount: product.priceCents, product_data: { name: product.name } } }],
      invoice_creation: { enabled: true },
      metadata: md,
      success_url: `${siteUrl}/dashboard?market=ok`,
      cancel_url: `${siteUrl}/dashboard?market=cancel`,
    });
    return { url: session.url };
  });

  // ── Buyer: my purchases for a project ───────────────────────────────────────
  app.get('/marketplace/my-purchases', { preHandler: requireRole() }, async (req) => {
    const p = await db();
    const rows = await p.projectProductPurchase.findMany({
      where: { buyerId: req.user.uid }, orderBy: { createdAt: 'desc' }, take: 200,
      include: { product: { select: { name: true, projectKey: true, showcaseProjectId: true } } },
    });
    return { purchases: rows.map((r) => ({ id: r.id, name: r.product?.name, status: r.status, delivery: r.delivery, createdAt: r.createdAt })) };
  });

  // ── Admin: product CRUD (owner-scoping is a Phase-2 refinement) ──────────────
  app.get('/admin/marketplace/products', { preHandler: requireRole('ADMIN') }, async (req) => {
    const p = await db();
    const where = {};
    if (req.query?.projectKey) where.projectKey = String(req.query.projectKey);
    if (req.query?.showcaseProjectId) where.showcaseProjectId = String(req.query.showcaseProjectId);
    const rows = await p.projectProduct.findMany({ where, orderBy: { createdAt: 'desc' }, take: 500, include: { _count: { select: { keys: true, purchases: true } } } });
    return { products: rows.map((r) => ({ ...r, externalSecret: r.externalSecret ? '••••' : null, keyCount: r._count.keys, purchaseCount: r._count.purchases, _count: undefined })) };
  });

  app.post('/admin/marketplace/products', { preHandler: requireRole('ADMIN') }, async (req, reply) => {
    const b = productSchema.safeParse(req.body);
    if (!b.success) return reply.code(400).send({ error: 'invalid_input', details: b.error.flatten() });
    if (!b.data.projectKey && !b.data.showcaseProjectId) return reply.code(400).send({ error: 'project_required' });
    const p = await db();
    const created = await p.projectProduct.create({ data: b.data });
    return { ok: true, product: created };
  });

  app.patch('/admin/marketplace/products/:id', { preHandler: requireRole('ADMIN') }, async (req, reply) => {
    const b = productSchema.partial().safeParse(req.body);
    if (!b.success) return reply.code(400).send({ error: 'invalid_input' });
    const p = await db();
    const exists = await p.projectProduct.findUnique({ where: { id: req.params.id } });
    if (!exists) return reply.code(404).send({ error: 'not_found' });
    const updated = await p.projectProduct.update({ where: { id: req.params.id }, data: b.data });
    return { ok: true, product: updated };
  });

  app.delete('/admin/marketplace/products/:id', { preHandler: requireRole('ADMIN') }, async (req) => {
    const p = await db();
    await p.projectProduct.delete({ where: { id: req.params.id } }).catch(() => {});
    return { ok: true };
  });

  // ── Admin: add keys to a product's pool ─────────────────────────────────────
  // ── Buyer: download a file they bought ───────────────────────────────────────
  //
  // The signed URL is minted HERE, per request, against a purchase that exists — not stored on
  // the product and not handed out at purchase time. A link that never expires is the thing
  // this delivery kind exists to avoid: pasted into `content` it would be forwardable for ever.
  app.get('/marketplace/purchases/:id/download', { preHandler: requireRole() }, async (req, reply) => {
    const p = await db();
    const purchase = await p.projectProductPurchase.findUnique({ where: { id: req.params.id }, include: { product: true } });
    if (!purchase || purchase.buyerId !== req.user.uid) return reply.code(404).send({ error: 'not_found' });
    if (purchase.status !== 'paid') return reply.code(409).send({ error: 'not_paid' });
    // The key comes from the PURCHASE, so replacing the product's file later does not silently
    // hand an old buyer a different file than the one they paid for.
    const key = purchase.delivery?.fileKey || purchase.product?.fileKey;
    if (!key) return reply.code(409).send({ error: 'no_file' });
    const url = await presignGet(key, DOWNLOAD_TTL).catch(() => null);
    if (!url) return reply.code(503).send({ error: 'storage_unavailable' });
    return { url, expiresInSec: DOWNLOAD_TTL, fileName: purchase.delivery?.fileName || purchase.product?.fileName || 'download' };
  });

  // ── Admin: attach the file a `file` product hands over ───────────────────────
  app.post('/admin/marketplace/products/:id/file', { preHandler: requireRole('ADMIN'), bodyLimit: 64 * 1024 * 1024 }, async (req, reply) => {
    const b = z.object({
      fileName: z.string().min(1).max(200),
      contentType: z.string().max(100).optional().default('application/octet-stream'),
      data: z.string().min(1), // base64
    }).safeParse(req.body);
    if (!b.success) return reply.code(400).send({ error: 'invalid_input' });
    const p = await db();
    const product = await p.projectProduct.findUnique({ where: { id: req.params.id } });
    if (!product) return reply.code(404).send({ error: 'not_found' });
    let buf;
    try { buf = Buffer.from(b.data.data, 'base64'); } catch { return reply.code(400).send({ error: 'bad_file' }); }
    // Checked BEFORE the object is written, and against the total minus whatever this product
    // already holds — replacing a 40 MB file with a 41 MB one must be judged on the one
    // megabyte it adds, not on the forty-one it would be if the old file were staying.
    const store = await marketplaceStorage(p);
    const delta = buf.length - Number(product.fileBytes || 0);
    if (store.capBytes > 0 && delta > 0 && store.usedBytes + delta > store.capBytes) {
      return reply.code(413).send({
        error: 'marketplace_storage_full',
        usedBytes: store.usedBytes, capBytes: store.capBytes, needBytes: delta,
      });
    }
    // The name is sanitised for the KEY only; the original is kept for the download's filename,
    // so a buyer gets back what the admin uploaded rather than a mangled version of it.
    const safe = String(b.data.fileName).replace(/[^\w.-]+/g, '_').slice(0, 80) || 'file';
    const key = `${FILE_PREFIX}/${product.id}/${crypto.randomUUID().replace(/-/g, '').slice(0, 12)}-${safe}`;
    try { await putObject(key, buf, b.data.contentType); }
    catch (e) { req.log.warn({ e: String(e) }, 'marketplace file store failed'); return reply.code(503).send({ error: 'storage_unavailable' }); }
    // The previous file is removed only after the new one is safely stored — the other order
    // loses the old file when the upload fails.
    if (product.fileKey && product.fileKey !== key) await deleteObject(product.fileKey).catch(() => {});
    const row = await p.projectProduct.update({ where: { id: product.id }, data: { fileKey: key, fileName: b.data.fileName.slice(0, 200), fileBytes: buf.length } });
    return { ok: true, fileName: row.fileName, bytes: buf.length, storage: await marketplaceStorage(p) };
  });

  /**
   * Mint keys into the pool, here, instead of pasting them in from somewhere else.
   *
   * `key_pool` could only be filled by hand: generate codes in another tool, paste them, and
   * hope nobody kept a copy of the list. `key_license` mints on demand but stores nothing —
   * which means no stock to show, no way to see what was handed out, and no way to revoke one.
   *
   * This is the middle both were missing: BCWEB generates them, keeps them, and hands them out
   * one at a time through the same race-safe claim the pool already uses. The alphabet drops
   * the characters people misread aloud (0/O, 1/I/L), which matters for something read off a
   * screen and typed into a game.
   *
   * Uniqueness is enforced by asking the database what it already has rather than by trusting
   * the odds — 31^20 is a comfortable space, but "comfortable" is not the same as "checked",
   * and a duplicate would hand two buyers the same key.
   */
  app.post('/admin/marketplace/products/:id/keys/mint', { preHandler: requireRole('ADMIN') }, async (req, reply) => {
    const b = z.object({
      count: z.number().int().min(1).max(1000),
      prefix: z.string().max(12).regex(/^[A-Z0-9-]*$/).optional().default(''),
    }).safeParse(req.body || {});
    if (!b.success) return reply.code(400).send({ error: 'invalid_input' });
    const p = await db();
    const product = await p.projectProduct.findUnique({ where: { id: req.params.id } });
    if (!product) return reply.code(404).send({ error: 'not_found' });

    const A = 'ABCDEFGHJKMNPQRSTUVWXYZ23456789';
    const group = () => Array.from({ length: 5 }, () => A[crypto.randomInt(A.length)]).join('');
    const make = () => `${b.data.prefix ? `${b.data.prefix}-` : ''}${group()}-${group()}-${group()}-${group()}`;

    const existing = new Set((await p.projectKey.findMany({ where: { productId: product.id }, select: { code: true } })).map((k) => k.code));
    const fresh = new Set();
    // Bounded: a pathological run of collisions must not spin. In practice the loop runs
    // `count` times.
    for (let i = 0; i < b.data.count * 20 && fresh.size < b.data.count; i++) {
      const c = make();
      if (!existing.has(c) && !fresh.has(c)) fresh.add(c);
    }
    if (fresh.size < b.data.count) return reply.code(500).send({ error: 'could_not_mint' });

    await p.projectKey.createMany({ data: [...fresh].map((code) => ({ productId: product.id, code })) });
    const [total, free] = await Promise.all([
      p.projectKey.count({ where: { productId: product.id } }),
      p.projectKey.count({ where: { productId: product.id, claimedAt: null } }),
    ]);
    await logAudit(p, req.user.uid, 'marketplace.keys_mint', `${product.name}: +${fresh.size}`, clientIp(req));
    return { ok: true, minted: fresh.size, total, free };
  });

  /** How full the marketplace's share of the disk is. Read-only; the cap is a hosting setting. */
  app.get('/admin/marketplace/storage', { preHandler: requireRole('ADMIN') }, async () => marketplaceStorage(await db()));

  app.post('/admin/marketplace/products/:id/keys', { preHandler: requireRole('ADMIN') }, async (req, reply) => {
    const codes = z.object({ codes: z.array(z.string().min(1).max(400)).max(5000) }).safeParse(req.body);
    if (!codes.success) return reply.code(400).send({ error: 'invalid_input' });
    const p = await db();
    const product = await p.projectProduct.findUnique({ where: { id: req.params.id } });
    if (!product) return reply.code(404).send({ error: 'not_found' });
    const clean = [...new Set(codes.data.codes.map((c) => c.trim()).filter(Boolean))];
    if (clean.length) await p.projectKey.createMany({ data: clean.map((code) => ({ productId: product.id, code })) });
    const [total, free] = await Promise.all([
      p.projectKey.count({ where: { productId: product.id } }),
      p.projectKey.count({ where: { productId: product.id, claimedAt: null } }),
    ]);
    return { ok: true, added: clean.length, total, free };
  });
}
