import { Link } from 'react-router-dom';
import { Lock, ShieldCheck, Cookie, Sparkles, Receipt, FileText } from 'lucide-react';
import { PageHeader, Button, Card } from '../ui/ui.jsx';
import { useI18n } from '../i18n.jsx';

/* ─────────────────────────  Legal  ───────────────────────── */
const LEGAL = {
  en: {
    privacy: { icon: Lock, title: 'Privacy Policy', body: [
      ['What we collect', 'An account requires your email and a display name. We store the content you submit (apps, plugins, themes, presets) and basic moderation records. Passwords are hashed with argon2id — never stored in plain text.'],
      ['Analytics we run', 'With your cookie consent we collect privacy-friendly, first-party, anonymous analytics on THIS website: the page path and referrer; a daily-rotating anonymous visitor hash (no persistent identifier); a coarse device / browser / operating-system type; an approximate location (country, region and city) derived from your IP address, which we do not store long-term for this purpose; anonymous in-page interaction signals (which elements are clicked, edited or submitted — never the actual values you type into fields); and basic performance metrics (Web Vitals — including, for the responsiveness metric, the IDENTITY of the element the slowest interaction landed on, such as “button: Save”, never the value of a field). It is aggregated to understand how the site is used and to fix problems — no third-party trackers, no advertising, no cross-site profiling, and no attempt to identify you personally. You can decline at any time and declining loses no functionality.'],
      ['Signed-in devices', 'When you sign in we record one row per device so you can see where your account is in use and end a session you do not recognise (Profile → Signed-in devices). That row holds the IP address the sign-in came from, an approximate location derived from it (country, region, city), your browser / operating system / device type, and the times the session started and was last active. This is kept for security — it is what lets you notice and stop an account takeover. You are the only ordinary reader of it: it is not shown to moderators, and it is not used for analytics or profiling. One exception, stated rather than buried: a SUPERADMIN — the highest staff tier, not a moderator — can view this list on an account and sign a device out, for account-recovery and abuse cases. Signing you out does not read your data or lock your account; you can sign straight back in. Signing a device out revokes it immediately; revoked rows are deleted after 30 days, and a session left idle past its token lifetime is deleted sooner. Unlike the analytics location described above, this one IS stored with your account for as long as the session lives.'],
      ['Content & files you host (Server-Repos)', 'When you host a Server-Repo or upload catalog files, we store those files as a neutral hosting provider so we can serve them for you. We do not inspect their contents beyond the moderation review and the automated integrity checks (SHA / per-file checksums) needed to run the platform, and we do not mine, sell, or repurpose them. If YOU place personal data inside your repo/files, you are the data controller for that data: you must have a lawful basis to store and distribute it, and you must not upload other people’s personal data without their consent or another legal basis. We process it only on your instructions, as your processor, to host and deliver it.'],
      ['Hosting & payments', 'If you purchase Server-Repo hosting, payment is processed by Stripe; we never see your card details. We store your subscription status, the timestamp at which you accepted these policies at checkout, and repo metadata.'],
      ['Answering a poll', 'A poll open to signed-in members records which options your account chose — that is one vote per account, and it is exact. A poll open to everybody has to keep out repeat votes without an account to count, so it stores a one-way fingerprint of your IP address and browser, salted per poll. It is not the daily-rotating analytics hash: it lasts as long as the poll, because a value that reset each night would let the same person vote again every day. It cannot be read back into an IP address, it is never used to identify or profile you, it is never joined to the analytics above, and it is not correlatable across polls. It is not cookie-consent gated, because it is not analytics: it is the mechanism that makes the count mean anything, and without it the poll could not be offered to people without accounts at all. It is deleted with the poll, and results are always reported with the anonymous half shown separately and labelled as an estimate.'],
      ['Using the public API', 'If you create an API key, we record how much each key is used — a per-day count of calls and errors, kept for as long as the key matters, so you and we can see what a key is doing. We also keep a SHORT-LIVED SAMPLE of individual calls: the method, the path, the status, how long it took, and the IP address the call came from. Retention is set by an administrator and is days, not months, and the sample exists to explain an incident rather than to build a history. The path is stored WITHOUT its query string, deliberately: private share links carry their secret there, and this table is readable by staff who have no access to those repositories.'],
      ['Your rights (GDPR)', 'You can request access to, correction of, or deletion of your personal data at any time by contacting us. Deleting your account removes your personal data and unpublishes your content.'],
      ['Retention', 'We keep data while your account is active and for as long as needed to provide the service or meet legal obligations.'],
      ['Closing your account, and coming back', 'Closing is scheduled 30 days ahead and reversible for that whole month. What happens at the end is ANONYMISATION rather than a row delete: your email, display name, profile and credentials are erased, while the records that must outlive an account — invoices, and the moderation history attached to what you published — are kept, because they are records about transactions and decisions rather than about your profile. One thing we keep is derived from your email: a one-way hash of the address, and nothing else. It exists so that if you sign up again with the same address we can recognise you and reattach your history — including any moderation record. We are stating that plainly rather than burying it, because it cuts both ways: it means a returning member keeps what they earned, and it means closing an account is not a way to leave a ban behind. Signing up with a different address starts genuinely fresh. The hash cannot be read back into your address, and it is used for nothing else.'],
      ['Security', 'We use reasonable technical and organisational measures to protect your data — passwords are hashed (argon2id), transport is encrypted, and access is restricted. No system is perfectly secure; if a breach materially affects you, we will notify you as required by law.'],
      ['Age', 'BetterCommunity is not directed at children. You must be at least 13 years old (or the minimum digital-consent age in your country) to create an account.'],
      ['Data processors', 'We rely on a small number of processors to run the service — Stripe (payments), our hosting/object-storage provider, and, if you opt in, Discord (account linking) and, in future, an analytics/Google tag. Each only receives the data needed for its function and is bound by a data-processing agreement.'],
      ['Make Your Own requests', 'If you use the paid "Make Your Own" service, we store the details you submit (product name, objective, description and any logo URL you provide), the conversation with our team, any files exchanged, and the payment records. We use them only to provide the service and keep them while your request is active and as needed for our legal obligations. Do not put other people’s personal data into a request without a lawful basis.'],
      ['Legal bases (GDPR Art. 6)', 'We process your data on these bases: performance of our contract with you (account, hosting, payments); your consent (optional analytics, Discord linking); our legitimate interests (security, abuse prevention, service improvement) balanced against your rights; and compliance with legal obligations. You can withdraw consent at any time without affecting prior processing.'],
      ['International transfers', 'Some processors (e.g. Stripe, or an analytics / Google tag if you enable it) may process data outside your country, including outside the EEA/UK. Where they do, transfers rely on appropriate safeguards such as the EU Standard Contractual Clauses or an adequacy decision.'],
      ['Your rights & how to exercise them', 'Under the GDPR/UK-GDPR you may access, rectify, erase, restrict or object to processing, withdraw consent, and request portability of your data. Reach us via the Contact page; we respond within one month. You also have the right to lodge a complaint with your local data-protection supervisory authority.'],
      ['No automated decisions', 'We do not carry out automated decision-making or profiling that produces legal or similarly significant effects on you.'],
      ['Data controller & contact', 'The data controller is the operator of BetterCommunity. For any privacy request or question — access, deletion, portability, or to withdraw consent — reach us through the Contact page.'],
    ] },
    terms: { icon: ShieldCheck, title: 'Terms of Service', body: [
      ['Accounts', 'You are responsible for activity under your account and for the content you submit. Keep your credentials safe.'],
      ['Content & moderation', 'Submissions are reviewed before publication. We may reject or remove content that is illegal, malicious, infringing, or violates these terms. You retain ownership of what you upload and grant us a licence to host and distribute it within the platform.'],
      ['Review & validation times', 'Every submission and update is queued for manual review and stays hidden (PENDING) until an admin approves it. We aim to review within 72 hours, but provide no guaranteed turnaround and may take longer during high volume. Plugin/theme files and hosted-repo content are automatically re-checked (SHA / per-file checksums) on every change and must pass before they can go live. We may re-review, re-validate, or unpublish previously approved content at any time.'],
      ['Copyright & hosted content rules', 'You may only upload or host content you own or are licensed to distribute. The following are strictly prohibited: copyrighted material without permission, paid/leaked third-party assets, malware or obfuscated payloads, illegal content, and anything infringing a trademark or another creator’s rights. Hosted Server-Repos must respect the original creators’ licences. We comply with takedown requests: rights holders can report infringing content and we will remove it promptly. Repeat infringers are banned and may have their repos and account terminated without refund.'],
      ['Hosting', 'Hosted Server-Repos are subject to the storage, upload and capacity limits we set. Updates require a valid SHA. Abuse, illegal content, or excessive resource use may lead to suspension.'],
      ['Data & content you host', 'You are solely responsible for everything you upload, host, or distribute through the service, including its legality and any personal data it contains. You warrant that you have the right to store and share it and that it complies with all applicable laws (including data-protection and copyright law). We act only as a neutral hosting/storage provider and, where your content contains personal data, as your data processor acting on your instructions — you remain the data controller. We do not back up your hosted data for you; keep your own copy. You agree to indemnify and hold us harmless from any third-party claim, loss, or liability arising out of the content or data you host.'],
      ['Downloads & use of software and content — at your own risk', 'BetterCommunity lets you download and use the Better* applications (such as BMM, BSM and BetterInstaller) and community-submitted content (mods, plugins, themes, presets and hosted Server-Repos). All of it is provided “as is”, with no warranty of fitness, safety, compatibility or result. You download, install and use it entirely at your own risk. To the maximum extent permitted by law we accept no responsibility for any consequence of downloading or using anything obtained through the platform — including damage to your device, operating system or other software, loss or corruption of files, game or save-file corruption, incompatibility, or any suspension, ban, or penalty imposed on you by a third-party game, storefront, service, or publisher. Verify what you install and keep your own backups.'],
      ['Third-party content & no endorsement', 'Community content is created and published by its authors, not by us. Our moderation and automated integrity checks aim to catch obvious abuse and malware, but they are not a guarantee of safety, quality, legality, or suitability, and listing or hosting content is never an endorsement of it. You alone are responsible for complying with the terms, licences, and rules of any third-party game, platform, mod loader, or software you use this content with — some modifications may breach those third parties’ own terms, and any resulting consequence (including account bans on those services) is yours alone.'],
      ['Accepting these terms', 'You must accept these Terms and the Payments & Refunds policy before you can pay for any hosting or feature. We record the date and time of your acceptance. If we materially change these terms, a new acceptance may be required before your next purchase.'],
      ['Commissioned work (Make Your Own)', 'The optional "Make Your Own" service lets you pay a consultation fee to discuss a product you want built (for example a Discord bot, an app, a website, or a custom job such as a code security review) and receive advice plus a written quote. The consultation fee pays for that advice and the quote only — it is NOT the price of the product, and no build work begins until you approve and pay the separate quote. Timelines are estimates, not guarantees. You must hold the rights to any materials you provide (names, logos, assets, and — for a security review — the code or system to be examined, which you confirm you are authorised to have tested), and you are responsible for the legality and intended use of what you ask us to build; we may decline or stop any request that is illegal, infringing, or abusive. Delivered work is provided "as is"; each quote states whether it includes source code. Unless a quote says otherwise, once you have paid in full you receive the right to use the delivered product for the purpose described, while we keep ownership of our pre-existing tools, libraries and general know-how. Security-review findings are best-effort and are never a guarantee that a product is free of vulnerabilities. Refunds for this service are covered in the Payments & Refunds policy.'],
      ['Payments', 'Hosting and listing features are billed via Stripe. Prices are shown before you confirm and may change with notice; a change never affects a period already paid for. No refunds for partial periods unless required by law — see the Payments & Refunds policy for the full detail.'],
      ['Payment failure & data retention', 'If a hosting subscription payment fails, you have 72 hours to renew it. After that window, the data stored for that subscription (hosted Server-Repo files and related content) is deleted without further notice and without backup.'],
      ['Acceptable use', 'You agree not to abuse the service: no scraping or automated bulk access beyond our documented APIs, no attempts to reverse-engineer, overload, probe, or circumvent quotas, sandboxing or integrity checks, and no uploading of malware, obfuscated payloads, or illegal content. We may rate-limit, throttle, suspend, or block abusive activity at any time.'],
      ['Enforcement', 'We enforce these terms strictly and at our sole discretion. Any violation may result in the immediate removal of content, suspension or permanent termination of your account and hosted repos — without prior notice and without refund — and, where the law requires, reporting to the competent authorities. Attempting to bypass moderation, integrity checks, quotas, or the sandbox is itself a violation. These measures are cumulative and in addition to any other remedy available to us.'],
      ['Governing law & changes', 'These terms are governed by the laws of our place of establishment, without regard to conflict-of-law rules. We may update these terms; material changes are announced and continued use after they take effect constitutes acceptance. If any provision is held unenforceable, the remainder stays in full force.'],
      ['Disclaimer & liability', 'The service is provided “as is” and “as available”, without warranties of any kind. To the maximum extent permitted by law, we are not liable for indirect, incidental, or consequential damages, and our total liability is limited to the amount you paid us in the 12 months preceding the claim.'],
    ] },
    cookies: { icon: Cookie, title: 'Cookie Policy', body: [
      ['What cookies are', 'Cookies and similar technologies (such as local storage) are small pieces of data stored in your browser. We group them by purpose below. You control the optional categories from the cookie banner and can change your choice at any time.'],
      ['1 · Strictly necessary', 'A single session cookie keeps you signed in and secures your form submissions. It is required for the site to work and cannot be switched off. Under the GDPR/ePrivacy rules no consent is needed for this category because it is essential to a service you asked for.'],
      ['2 · Analytics / statistics (optional — off by default)', 'Only if you accept the Analytics category do we enable privacy-friendly, first-party analytics: page path and referrer, a daily-rotating anonymous visitor hash, coarse device / browser / OS, approximate location (country / region / city) from your IP, anonymous in-page interaction signals (which elements are clicked/edited/submitted — never the values you type), and performance metrics (Web Vitals). Your choice is remembered in local storage, not in a tracking cookie, and you can decline with no loss of functionality.'],
      ['Third-party tags (Google Tag Manager)', 'When configured, we load Google Tag Manager as a third-party measurement tag. Its scripts and cookies load ONLY after you opt in to the Analytics category above — never before. Declining, or simply ignoring the banner, keeps it disabled. Google acts as our processor; some data may be transferred outside the EEA under appropriate safeguards (see the Privacy Policy). You can withdraw consent at any time, and we treat a Global Privacy Control / Do-Not-Track signal as an automatic decline.'],
      ['Managing your consent', 'Your preference is stored per browser. To review or change it, clear this site’s storage (or use your browser’s site-data controls) and reload — the banner reappears. Withdrawing consent stops any further analytics collection immediately.'],
      ['No advertising', 'We never use advertising, cross-site, or social-media tracking cookies, and we never sell your data.'],
    ] },
    about: { icon: Sparkles, title: 'About us', body: [
      ['What BetterCommunity is', 'BetterCommunity is the shared home for the Better* ecosystem — a hub where the community discovers, shares, and hosts content for tools like Better Mods Manager (BMM), Better Sound Maker (BSM), and BetterInstaller. One account, one place: browse the catalogs, publish your own mods, plugins, themes and presets, and spin up a hosted Server-Repo.'],
      ['Our mission', 'To give creators a clean, honest, no-nonsense platform: no ads, no dark patterns, no selling your data. Every submission is human-reviewed before it goes live, integrity-checked on every change, and the whole thing is built to stay fast and lightweight.'],
      ['The projects', 'BMM manages mods for supported games with a full plugin/theme system. BSM is a sound-preset catalog. BetterInstaller is a fast, modern installer for the suite. Server-Repos let creators host their own repositories with us, billed only for what they use. Every catalog is filled by the community and curated by a small moderation team, and contributors are credited on each project page.'],
      ['Open & transparent', 'Our moderation rules, pricing, and privacy practices are all documented in these legal pages — no surprises. Found a problem or have an idea? The Contact page and our Discord are the fastest ways to reach us.'],
      ['Support the project', 'BetterCommunity is community-funded. Hosting costs are covered by the paid Server-Repo plans and by donations on Ko-fi. Every tip goes straight to keeping the servers running — thank you.'],
    ] },
    refunds: { icon: Receipt, title: 'Payments & Refunds', body: [
      ['How billing works', 'Two things are paid: (1) hosted Server-Repos and storage pools, billed by the capacity, bandwidth and features you choose; and (2) our-hosted catalog file storage above the free floor, and optional "featured" boosts. Everything is processed by Stripe — we never see or store your card details.'],
      ['Prices & currency', 'Prices are shown before you confirm, in the currency your payment method supports. Recurring plans renew automatically until you cancel. We may change prices with advance notice; a change never affects a period you have already paid for.'],
      ['If a price goes up', 'We email every affected subscriber before a price increase takes effect, at the address on the account, and post the same notice inside your account — an email can be missed, and the month it is missed in is the notice period. The notice states the current price, the new one, and the exact date it changes. The new price applies from your NEXT renewal, never to a period already paid for, and never mid-term on a prepaid plan. You can cancel before that renewal and keep your service until the end of the period you have paid — cancelling is always enough to decline an increase. Some plans are priced from our published per-GB and per-Mbps rates rather than a fixed figure, so their price follows those rates; the same notice and the same next-renewal rule apply.'],
      ['Free tier', 'Every account gets a free storage floor for hosting and a free catalog-upload floor — you only pay for what exceeds it. The free tier is genuinely free: no card required, no trial that silently converts.'],
      ['Cancelling', 'You can cancel a hosting subscription at any time from your dashboard. Cancellation stops the next renewal; your repo stays online until the end of the period you already paid for, then is taken offline.'],
      ['If your account is suspended or banned', 'A sanction stops the service, so it ends the money too: any active subscription is cancelled when a suspension or a ban is applied, and you are not billed again. What differs between the two is access — a SUSPENSION leaves you able to sign in, so you can read the reason, appeal it and download your invoices, while a BAN does not. In both cases your repositories, catalogs and items are SUSPENDED rather than deleted: nothing is destroyed, and if the sanction is lifted every one of them returns to the state it was in beforehand — a repository that was offline comes back offline. Subscriptions are the exception: they are cancelled at the payment provider and are not resurrected, so you would take out a new one. The period you had already paid for is not refunded automatically when the sanction is for cause; if you believe it was a mistake, contact us and a person will look.'],
      ['Refund policy', 'Because hosting is a consumable, capacity-reserving service, we do not refund partial or unused periods unless the law requires it or we are clearly at fault (e.g. a billing error or an extended outage caused by us). If you think you were charged in error, contact us within 14 days and we will investigate and make it right.'],
      ['Failed payments & data deletion', 'If a renewal payment fails, you have 72 hours to update your payment method and renew. After that window the data stored for that subscription (hosted Server-Repo files and related content) is deleted without further notice and without backup — so keep your own copy.'],
      ['Consultations & commissions (Make Your Own)', 'The consultation fee buys advice and a quote — a service we perform as soon as we reply to you. Once we have provided that advice it is non-refundable; if we are unable to help at all and give no advice, we refund it. A separate quote payment commissions bespoke work made to your instructions: once that work has begun it is non-refundable for the part already performed. If we fail to deliver what the quote describes and cannot put it right, we refund the portion not delivered. Approving a quote is a request for us to start immediately, which reduces or ends any statutory withdrawal right for work already done, as permitted by consumer law.'],
      ['Statutory withdrawal (EU/UK)', 'Where a legal right of withdrawal applies to a purchase of digital services, you may request cancellation within the statutory period. Note that by starting a hosting subscription you ask us to begin the service immediately, which can reduce or end that withdrawal right for the portion already provided — as permitted by consumer law.'],
      ['How to request a refund', 'Reach us through the Contact page with your account email and the approximate date/amount of the charge. We respond within a few business days. Approved refunds are returned to the original payment method via Stripe.'],
      ['Chargebacks', 'If something looks wrong, please contact us first — we can almost always resolve it faster than a bank dispute. Opening a chargeback without contacting us may result in suspension of the associated account and repos pending resolution.'],
    ] },
  },
  fr: {
    privacy: { icon: Lock, title: 'Politique de confidentialité', body: [
      ['Ce que nous collectons', 'Un compte requiert ton e-mail et un nom affiché. Nous stockons le contenu que tu soumets (apps, plugins, thèmes, presets) et des données de modération. Les mots de passe sont hachés avec argon2id — jamais en clair.'],
      ['Les statistiques que nous faisons', 'Avec ton accord cookies, nous collectons sur CE site des statistiques internes, anonymes et respectueuses de la vie privée : le chemin de page et le référent ; un hachage de visiteur anonyme qui change chaque jour (aucun identifiant persistant) ; un type d’appareil / navigateur / système approximatif ; une localisation approximative (pays, région et ville) dérivée de ton adresse IP, que nous ne conservons pas durablement à cette fin ; des signaux d’interaction anonymes dans la page (quels éléments sont cliqués, édités ou soumis — jamais les valeurs que tu saisis) ; et des mesures de performance de base (Web Vitals — dont, pour la mesure de réactivité, l’IDENTITÉ de l’élément sur lequel l’interaction la plus lente a porté, par exemple « button: Save », jamais la valeur d’un champ). Elles sont agrégées pour comprendre l’usage du site et corriger les problèmes — aucun pisteur tiers, aucune publicité, aucun profilage inter-sites, et aucune tentative de t’identifier personnellement. Tu peux refuser à tout moment sans perte de fonctionnalité.'],
      ['Appareils connectés', 'Lorsque tu te connectes, nous enregistrons une ligne par appareil afin que tu puisses voir où ton compte est utilisé et mettre fin à une session que tu ne reconnais pas (Profil → Appareils connectés). Cette ligne contient l’adresse IP à l’origine de la connexion, une localisation approximative qui en découle (pays, région, ville), ton navigateur / système / type d’appareil, ainsi que les dates de début et de dernière activité de la session. C’est conservé pour des raisons de sécurité — c’est ce qui te permet de repérer et d’arrêter un détournement de compte. Tu en es le seul lecteur ordinaire : ce n’est pas montré aux modérateurs, et ce n’est utilisé ni pour des statistiques ni pour du profilage. Une exception, énoncée plutôt qu’enfouie : un SUPERADMIN — le rang d’équipe le plus élevé, pas un modérateur — peut consulter cette liste sur un compte et déconnecter un appareil, pour les cas de récupération de compte et d’abus. Te déconnecter ne lit pas tes données et ne verrouille pas ton compte ; tu peux te reconnecter immédiatement. Déconnecter un appareil le révoque immédiatement ; les lignes révoquées sont supprimées au bout de 30 jours, et une session inactive au-delà de la durée de vie de son jeton l’est plus tôt. Contrairement à la localisation statistique décrite plus haut, celle-ci EST conservée avec ton compte tant que la session existe.'],
      ['Contenu & fichiers que tu héberges (Server-Repos)', 'Quand tu héberges un Server-Repo ou envoies des fichiers de catalogue, nous stockons ces fichiers en tant qu’hébergeur neutre afin de les servir pour toi. Nous n’inspectons pas leur contenu au-delà de la revue de modération et des contrôles d’intégrité automatiques (SHA / checksums par fichier) nécessaires au fonctionnement de la plateforme, et nous ne les exploitons, vendons ni réutilisons jamais. Si TU places des données personnelles dans ton dépôt/tes fichiers, tu en es le responsable de traitement : tu dois disposer d’une base légale pour les stocker et les distribuer, et tu ne dois pas envoyer les données personnelles d’autrui sans leur consentement ou une autre base légale. Nous ne les traitons que sur tes instructions, en tant que sous-traitant, pour les héberger et les diffuser.'],
      ['Hébergement & paiements', 'Si tu paies un hébergement de Server-Repo, le paiement est traité par Stripe ; nous ne voyons jamais ta carte. Nous stockons l’état de ton abonnement, l’horodatage de ton acceptation de ces politiques au paiement, et les métadonnées du dépôt.'],
      ['Répondre à un sondage', 'Un sondage réservé aux membres connectés enregistre les options choisies par ton compte — une voix par compte, et c’est exact. Un sondage ouvert à tous doit écarter les votes répétés sans compte à compter : il stocke donc une empreinte à sens unique de ton adresse IP et de ton navigateur, salée par sondage. Ce n’est pas le hachage statistique qui tourne chaque jour : elle dure autant que le sondage, parce qu’une valeur remise à zéro chaque nuit laisserait la même personne revoter tous les jours. Elle ne peut pas être retransformée en adresse IP, ne sert jamais à t’identifier ni à te profiler, n’est jamais rapprochée des statistiques ci-dessus, et n’est pas corrélable d’un sondage à l’autre. Elle n’est pas soumise au consentement cookies, parce que ce ne sont pas des statistiques : c’est le mécanisme qui donne un sens au décompte, et sans lui le sondage ne pourrait pas être proposé aux personnes sans compte. Elle est supprimée avec le sondage, et les résultats affichent toujours la part anonyme à part, présentée comme une estimation.'],
      ['Utiliser l’API publique', 'Si tu crées une clé API, nous enregistrons son usage — un compteur quotidien d’appels et d’erreurs, conservé tant que la clé compte, pour que toi et nous puissions voir ce qu’elle fait. Nous gardons aussi un ÉCHANTILLON DE COURTE DURÉE d’appels individuels : la méthode, le chemin, le statut, la durée et l’adresse IP d’origine. La durée de conservation est réglée par un administrateur et se compte en jours, pas en mois : cet échantillon sert à expliquer un incident, pas à constituer un historique. Le chemin est stocké SANS sa chaîne de requête, volontairement : les liens de partage privés y portent leur secret, et cette table est lisible par des membres de l’équipe qui n’ont aucun accès à ces dépôts.'],
      ['Tes droits (RGPD)', 'Tu peux demander l’accès, la rectification ou la suppression de tes données à tout moment en nous contactant. Supprimer ton compte efface tes données personnelles et dépublie ton contenu.'],
      ['Conservation', 'Nous conservons les données tant que ton compte est actif et aussi longtemps que nécessaire au service ou à nos obligations légales.'],
      ['Fermer ton compte, et revenir', 'Une fermeture est planifiée 30 jours à l’avance et reste annulable pendant tout ce mois. Ce qui se produit au terme est une ANONYMISATION, pas une suppression de ligne : ton e-mail, ton nom affiché, ton profil et tes identifiants sont effacés, tandis que ce qui doit survivre à un compte — les factures, et l’historique de modération attaché à ce que tu as publié — est conservé, parce que ce sont des enregistrements sur des transactions et des décisions, pas sur ton profil. Une chose conservée dérive de ton e-mail : un hachage à sens unique de l’adresse, et rien d’autre. Il existe pour que, si tu recrées un compte avec la même adresse, nous puissions te reconnaître et rattacher ton historique — y compris un éventuel dossier de modération. Nous le disons franchement plutôt que de l’enfouir, parce que cela coupe dans les deux sens : un membre qui revient retrouve ce qu’il avait, et fermer un compte n’est pas un moyen de laisser une sanction derrière soi. S’inscrire avec une autre adresse repart vraiment de zéro. Ce hachage ne peut pas être retransformé en ton adresse, et ne sert à rien d’autre.'],
      ['Sécurité', 'Nous utilisons des mesures techniques et organisationnelles raisonnables pour protéger tes données — mots de passe hachés (argon2id), transport chiffré, accès restreint. Aucun système n’est parfaitement sûr ; en cas de violation te concernant significativement, nous te préviendrons conformément à la loi.'],
      ['Âge', 'BetterCommunity ne s’adresse pas aux enfants. Tu dois avoir au moins 13 ans (ou l’âge minimum de consentement numérique dans ton pays) pour créer un compte.'],
      ['Sous-traitants', 'Nous nous appuyons sur quelques sous-traitants — Stripe (paiements), notre hébergeur/stockage objet, et, si tu y consens, Discord (liaison de compte) et, à l’avenir, un tag analytics/Google. Chacun ne reçoit que les données nécessaires à sa fonction et est lié par un accord de traitement.'],
      ['Demandes Make Your Own', 'Si tu utilises le service payant « Make Your Own », nous stockons les informations que tu soumets (nom du produit, objectif, description et l’URL de logo éventuelle), la conversation avec notre équipe, les fichiers échangés et les enregistrements de paiement. Nous ne les utilisons que pour fournir le service et les conservons tant que ta demande est active et selon nos obligations légales. Ne place pas de données personnelles d’autrui dans une demande sans base légale.'],
      ['Bases légales (RGPD Art. 6)', 'Nous traitons tes données sur ces bases : l’exécution de notre contrat (compte, hébergement, paiements) ; ton consentement (statistiques optionnelles, liaison Discord) ; nos intérêts légitimes (sécurité, prévention des abus, amélioration du service) mis en balance avec tes droits ; et le respect de nos obligations légales. Tu peux retirer ton consentement à tout moment sans affecter les traitements antérieurs.'],
      ['Transferts internationaux', 'Certains sous-traitants (ex. Stripe, ou un tag analytics/Google si tu l’actives) peuvent traiter des données hors de ton pays, y compris hors EEE/Royaume-Uni. Le cas échéant, les transferts reposent sur des garanties appropriées comme les Clauses Contractuelles Types de l’UE ou une décision d’adéquation.'],
      ['Tes droits & comment les exercer', 'Au titre du RGPD, tu peux accéder à tes données, les rectifier, les effacer, en limiter ou t’opposer au traitement, retirer ton consentement et demander leur portabilité. Contacte-nous via la page Contact ; nous répondons sous un mois. Tu as aussi le droit d’introduire une réclamation auprès de ton autorité de protection des données (en France, la CNIL).'],
      ['Pas de décision automatisée', 'Nous ne procédons à aucune décision automatisée ni profilage produisant des effets juridiques ou significatifs à ton égard.'],
      ['Responsable de traitement & contact', 'Le responsable de traitement est l’opérateur de BetterCommunity. Pour toute demande — accès, suppression, portabilité, ou retrait de consentement — contacte-nous via la page Contact.'],
    ] },
    terms: { icon: ShieldCheck, title: 'Conditions d’utilisation', body: [
      ['Comptes', 'Tu es responsable de l’activité de ton compte et du contenu que tu soumets. Garde tes identifiants en sécurité.'],
      ['Contenu & modération', 'Les soumissions sont vérifiées avant publication. Nous pouvons refuser ou retirer tout contenu illégal, malveillant, contrefaisant ou contraire aux présentes conditions. Tu restes propriétaire de ce que tu envoies et nous accordes une licence pour l’héberger et le distribuer sur la plateforme.'],
      ['Délais de vérification & validation', 'Chaque soumission et mise à jour passe en revue manuelle et reste masquée (EN ATTENTE) jusqu’à approbation par un administrateur. Nous visons une revue sous 72 heures, sans délai garanti, et cela peut être plus long en cas de forte affluence. Les fichiers de plugins/thèmes et le contenu des dépôts hébergés sont re-vérifiés automatiquement (SHA / checksums par fichier) à chaque changement et doivent être valides avant mise en ligne. Nous pouvons re-vérifier, re-valider ou dépublier un contenu déjà approuvé à tout moment.'],
      ['Droits d’auteur & règles de contenu hébergé', 'Tu ne peux héberger ou envoyer que du contenu que tu possèdes ou que tu es autorisé à distribuer. Sont strictement interdits : tout contenu protégé par le droit d’auteur sans autorisation, les assets tiers payants ou leakés, les malwares ou charges obfusquées, les contenus illégaux, et tout ce qui enfreint une marque ou les droits d’un autre créateur. Les Server-Repos hébergés doivent respecter les licences des créateurs originaux. Nous traitons les demandes de retrait : les ayants droit peuvent signaler un contenu contrefaisant, que nous retirerons rapidement. Les récidivistes sont bannis et peuvent voir leurs dépôts et leur compte résiliés sans remboursement.'],
      ['Hébergement', 'Les Server-Repos hébergés sont soumis aux limites de stockage, d’upload et de capacité que nous fixons. Les mises à jour exigent un SHA valide. Tout abus, contenu illégal ou usage excessif peut entraîner une suspension.'],
      ['Données & contenu que tu héberges', 'Tu es seul responsable de tout ce que tu envoies, héberges ou distribues via le service, y compris sa légalité et les données personnelles qu’il contient. Tu garantis avoir le droit de le stocker et le partager, et sa conformité à toutes les lois applicables (protection des données et droit d’auteur inclus). Nous agissons uniquement comme hébergeur/stockage neutre et, lorsque ton contenu contient des données personnelles, comme ton sous-traitant agissant sur tes instructions — tu restes le responsable de traitement. Nous ne sauvegardons pas tes données hébergées à ta place ; garde ta propre copie. Tu acceptes de nous garantir et de nous tenir indemnes de toute réclamation, perte ou responsabilité d’un tiers découlant du contenu ou des données que tu héberges.'],
      ['Téléchargements & usage des logiciels et contenus — à tes risques', 'BetterCommunity te permet de télécharger et d’utiliser les applications Better* (comme BMM, BSM et BetterInstaller) et le contenu soumis par la communauté (mods, plugins, thèmes, presets et Server-Repos hébergés). Tout cela est fourni « tel quel », sans aucune garantie d’adéquation, de sécurité, de compatibilité ou de résultat. Tu le télécharges, l’installes et l’utilises entièrement à tes propres risques. Dans la limite permise par la loi, nous n’assumons aucune responsabilité pour les conséquences du téléchargement ou de l’utilisation de quoi que ce soit obtenu via la plateforme — y compris dommages à ton appareil, ton système d’exploitation ou tes autres logiciels, perte ou corruption de fichiers, corruption de jeu ou de sauvegardes, incompatibilité, ou toute suspension, tout bannissement ou toute sanction infligés par un jeu, une boutique, un service ou un éditeur tiers. Vérifie ce que tu installes et garde tes propres sauvegardes.'],
      ['Contenu tiers & absence d’endossement', 'Le contenu communautaire est créé et publié par ses auteurs, pas par nous. Notre modération et nos contrôles d’intégrité automatiques visent à détecter les abus et malwares évidents, mais ils ne garantissent ni la sécurité, ni la qualité, ni la légalité, ni l’adéquation, et le fait de lister ou d’héberger un contenu ne vaut jamais approbation. Tu es seul responsable du respect des conditions, licences et règles de tout jeu, plateforme, mod loader ou logiciel tiers avec lequel tu utilises ce contenu — certaines modifications peuvent enfreindre les conditions de ces tiers, et toute conséquence qui en découle (y compris un bannissement de compte sur ces services) t’incombe seul.'],
      ['Acceptation des présentes conditions', 'Tu dois accepter les présentes Conditions et la politique Paiements & Remboursements avant de pouvoir payer un hébergement ou une option. Nous enregistrons la date et l’heure de ton acceptation. En cas de changement important, une nouvelle acceptation peut être requise avant ton prochain achat.'],
      ['Travaux sur commande (Make Your Own)', 'Le service optionnel « Make Your Own » te permet de payer des frais de consultation pour discuter d’un produit que tu souhaites faire créer (par exemple un bot Discord, une application, un site web, ou un travail sur mesure comme une revue de sécurité de code) et recevoir un conseil ainsi qu’un devis écrit. Les frais de consultation paient ce conseil et le devis uniquement — ce n’est PAS le prix du produit, et aucune création ne démarre tant que tu n’as pas validé et payé le devis séparé. Les délais sont des estimations, pas des garanties. Tu dois détenir les droits sur tout élément que tu fournis (noms, logos, ressources et — pour une revue de sécurité — le code ou le système à examiner, dont tu confirmes être autorisé à demander l’analyse), et tu es responsable de la légalité et de l’usage prévu de ce que tu demandes ; nous pouvons refuser ou arrêter toute demande illégale, contrefaisante ou abusive. Le travail livré est fourni « tel quel » ; chaque devis indique s’il inclut le code source. Sauf mention contraire du devis, une fois le paiement intégral effectué tu obtiens le droit d’utiliser le produit livré pour l’usage décrit, tandis que nous conservons la propriété de nos outils, bibliothèques et savoir-faire préexistants. Les conclusions d’une revue de sécurité sont fournies au mieux et ne garantissent jamais l’absence de vulnérabilités. Les remboursements de ce service sont traités dans la politique Paiements & Remboursements.'],
      ['Paiements', 'L’hébergement et la mise en avant sont facturés via Stripe. Les prix sont affichés avant confirmation et peuvent changer avec préavis ; un changement n’affecte jamais une période déjà payée. Pas de remboursement des périodes partielles, sauf obligation légale — voir la politique Paiements & Remboursements pour le détail complet.'],
      ['Échec de paiement & conservation des données', 'Si le paiement d’un abonnement d’hébergement échoue, vous disposez de 72 heures pour le renouveler. Passé ce délai, les données stockées pour cet abonnement (fichiers de Server-Repo hébergés et contenu associé) sont supprimées sans préavis ni sauvegarde.'],
      ['Usage acceptable', 'Tu t’engages à ne pas abuser du service : pas de scraping ni d’accès automatisé massif au-delà de nos API documentées, aucune tentative de rétro-ingénierie, de surcharge, de sondage ou de contournement des quotas, du bac à sable ou des contrôles d’intégrité, et aucun envoi de malware, de charge obfusquée ou de contenu illégal. Nous pouvons limiter, brider, suspendre ou bloquer toute activité abusive à tout moment.'],
      ['Application des règles', 'Nous appliquons ces conditions de manière stricte et à notre entière discrétion. Toute violation peut entraîner le retrait immédiat du contenu, la suspension ou la résiliation définitive de votre compte et de vos dépôts hébergés — sans préavis ni remboursement — et, lorsque la loi l’exige, un signalement aux autorités compétentes. Tenter de contourner la modération, les contrôles d’intégrité, les quotas ou le bac à sable constitue en soi une violation. Ces mesures sont cumulatives et s’ajoutent à tout autre recours dont nous disposons.'],
      ['Droit applicable & modifications', 'Ces conditions sont régies par le droit de notre lieu d’établissement, sans égard aux règles de conflit de lois. Nous pouvons les mettre à jour ; les changements importants sont annoncés et la poursuite de l’utilisation vaut acceptation. Si une clause est jugée inapplicable, le reste demeure pleinement en vigueur.'],
      ['Avertissement & responsabilité', 'Le service est fourni « tel quel » et « selon disponibilité », sans garantie d’aucune sorte. Dans la limite permise par la loi, nous ne sommes pas responsables des dommages indirects ou accessoires, et notre responsabilité totale est limitée aux sommes que vous nous avez versées durant les 12 mois précédant la réclamation.'],
    ] },
    cookies: { icon: Cookie, title: 'Politique de cookies', body: [
      ['Ce que sont les cookies', 'Les cookies et technologies similaires (comme le stockage local) sont de petites données conservées dans ton navigateur. Nous les regroupons ci-dessous par finalité. Tu contrôles les catégories optionnelles depuis la bannière cookies et peux changer ton choix à tout moment.'],
      ['1 · Strictement nécessaires', 'Un seul cookie de session te garde connecté et sécurise l’envoi des formulaires. Il est indispensable au fonctionnement du site et ne peut être désactivé. Selon le RGPD/ePrivacy, aucun consentement n’est requis pour cette catégorie car elle est essentielle à un service que tu as demandé.'],
      ['2 · Statistiques (optionnel — désactivé par défaut)', 'Uniquement si tu acceptes la catégorie Statistiques, nous activons des statistiques internes respectueuses de la vie privée : chemin de page et référent, un hachage de visiteur anonyme changeant chaque jour, appareil / navigateur / système approximatif, localisation approximative (pays / région / ville) depuis ton IP, signaux d’interaction anonymes dans la page (quels éléments sont cliqués/édités/soumis — jamais les valeurs saisies), et mesures de performance (Web Vitals). Ton choix est mémorisé dans le stockage local, pas dans un cookie de pistage, et tu peux refuser sans perte de fonctionnalité.'],
      ['Tags tiers (Google Tag Manager)', 'Quand il est configuré, nous chargeons Google Tag Manager comme tag de mesure tiers. Ses scripts et cookies ne se chargent QU’APRÈS ton opt-in à la catégorie Statistiques ci-dessus — jamais avant. Refuser, ou simplement ignorer la bannière, le garde désactivé. Google agit comme notre sous-traitant ; certaines données peuvent être transférées hors EEE sous garanties appropriées (voir la Politique de confidentialité). Tu peux retirer ton consentement à tout moment, et nous traitons un signal Global Privacy Control / Do-Not-Track comme un refus automatique.'],
      ['Gérer ton consentement', 'Ta préférence est stockée par navigateur. Pour la revoir ou la changer, vide le stockage de ce site (ou utilise les réglages de données de site de ton navigateur) et recharge — la bannière réapparaît. Retirer le consentement arrête immédiatement toute collecte de statistiques.'],
      ['Aucune publicité', 'Nous n’utilisons jamais de cookies publicitaires, inter-sites ou de pistage social, et nous ne vendons jamais tes données.'],
    ] },
    about: { icon: Sparkles, title: 'À propos', body: [
      ['Ce qu’est BetterCommunity', 'BetterCommunity est la maison commune de l’écosystème Better* — un hub où la communauté découvre, partage et héberge du contenu pour des outils comme Better Mods Manager (BMM), Better Sound Maker (BSM) et BetterInstaller. Un seul compte, un seul endroit : parcours les catalogues, publie tes mods, plugins, thèmes et presets, et lance un Server-Repo hébergé.'],
      ['Notre mission', 'Offrir aux créateurs une plateforme claire et honnête : pas de pub, pas de dark patterns, jamais de revente de tes données. Chaque soumission est vérifiée par un humain avant mise en ligne, re-contrôlée à chaque changement, et l’ensemble est conçu pour rester rapide et léger.'],
      ['Les projets', 'BMM gère les mods des jeux pris en charge avec un vrai système de plugins/thèmes. BSM est un catalogue de presets sonores. BetterInstaller est un installeur moderne et rapide pour la suite. Les Server-Repos permettent aux créateurs d’héberger leurs propres dépôts chez nous, facturés uniquement selon l’usage. Chaque catalogue est rempli par la communauté et curé par une petite équipe de modération, et les contributeurs sont crédités sur chaque page de projet.'],
      ['Ouvert & transparent', 'Nos règles de modération, nos tarifs et nos pratiques de confidentialité sont tous documentés dans ces pages légales — aucune surprise. Un problème ou une idée ? La page Contact et notre Discord sont les moyens les plus rapides de nous joindre.'],
      ['Soutenir le projet', 'BetterCommunity est financé par la communauté. Les coûts d’hébergement sont couverts par les offres Server-Repo payantes et par les dons sur Ko-fi. Chaque don sert directement à faire tourner les serveurs — merci.'],
    ] },
    refunds: { icon: Receipt, title: 'Paiements & Remboursements', body: [
      ['Fonctionnement de la facturation', 'Deux choses sont payantes : (1) les Server-Repos et pools de stockage hébergés, facturés selon la capacité, la bande passante et les options choisies ; et (2) le stockage de fichiers de catalogue chez nous au-delà du seuil gratuit, ainsi que les mises en avant « featured » optionnelles. Tout est traité par Stripe — nous ne voyons ni ne stockons jamais ta carte.'],
      ['Prix & devise', 'Les prix sont affichés avant confirmation, dans la devise prise en charge par ton moyen de paiement. Les offres récurrentes se renouvellent automatiquement jusqu’à résiliation. Nous pouvons modifier les prix avec préavis ; un changement n’affecte jamais une période déjà payée.'],
      ['Si un prix augmente', "Nous prévenons par e-mail chaque abonné concerné avant qu'une hausse ne prenne effet, à l'adresse du compte, et le même avis apparaît dans ton compte — un e-mail peut passer inaperçu, et le mois où il passe inaperçu est justement celui du préavis. L'avis indique le prix actuel, le nouveau, et la date exacte du changement. Le nouveau prix s'applique à partir de ton PROCHAIN renouvellement, jamais à une période déjà payée, et jamais en cours de terme sur une formule prépayée. Tu peux résilier avant ce renouvellement et conserver le service jusqu'à la fin de la période payée — résilier suffit toujours à refuser une hausse. Certaines formules sont tarifées à partir de nos taux publiés par Go et par Mbps plutôt qu'à un montant fixe : leur prix suit donc ces taux, avec le même préavis et la même règle du prochain renouvellement."],
      ['Offre gratuite', 'Chaque compte reçoit un seuil de stockage gratuit pour l’hébergement et un seuil gratuit d’upload de catalogue — tu ne paies que ce qui dépasse. L’offre gratuite est réellement gratuite : aucune carte requise, aucun essai qui se transforme silencieusement en abonnement.'],
      ['Résiliation', 'Tu peux résilier un abonnement d’hébergement à tout moment depuis ton tableau de bord. La résiliation stoppe le prochain renouvellement ; ton dépôt reste en ligne jusqu’à la fin de la période déjà payée, puis est mis hors ligne.'],
      ['Si ton compte est suspendu ou banni', 'Une sanction arrête le service, donc elle arrête aussi l’argent : tout abonnement actif est résilié au moment où une suspension ou un bannissement est appliqué, et tu n’es plus prélevé. Ce qui diffère entre les deux, c’est l’accès — une SUSPENSION te laisse te connecter, pour lire le motif, contester et récupérer tes factures ; un BANNISSEMENT non. Dans les deux cas, tes dépôts, catalogues et éléments sont SUSPENDUS et non supprimés : rien n’est détruit, et si la sanction est levée, chacun retrouve l’état où il était — un dépôt qui était hors ligne revient hors ligne. Les abonnements sont l’exception : ils sont résiliés chez le prestataire de paiement et ne sont pas rétablis, tu devrais en reprendre un. La période déjà payée n’est pas remboursée automatiquement quand la sanction est motivée ; si tu penses qu’il y a erreur, contacte-nous et une personne regardera.'],
      ['Politique de remboursement', 'L’hébergement étant un service consommable qui réserve de la capacité, nous ne remboursons pas les périodes partielles ou inutilisées, sauf si la loi l’exige ou si nous sommes clairement en faute (ex. erreur de facturation ou panne prolongée de notre fait). Si tu penses avoir été débité par erreur, contacte-nous sous 14 jours et nous rectifierons.'],
      ['Échec de paiement & suppression des données', 'Si un renouvellement échoue, tu disposes de 72 heures pour mettre à jour ton moyen de paiement et renouveler. Passé ce délai, les données stockées pour cet abonnement (fichiers de Server-Repo hébergés et contenu associé) sont supprimées sans préavis ni sauvegarde — garde donc ta propre copie.'],
      ['Consultations & commandes (Make Your Own)', 'Les frais de consultation paient un conseil et un devis — un service que nous fournissons dès que nous te répondons. Une fois ce conseil fourni, ils ne sont pas remboursables ; si nous ne pouvons pas t’aider du tout et ne donnons aucun conseil, nous les remboursons. Le paiement d’un devis commande un travail sur mesure réalisé selon tes instructions : une fois ce travail commencé, il n’est pas remboursable pour la part déjà effectuée. Si nous ne livrons pas ce que décrit le devis et ne pouvons pas y remédier, nous remboursons la part non livrée. Valider un devis vaut demande de commencer immédiatement, ce qui réduit ou supprime tout droit de rétractation légal pour le travail déjà réalisé, comme le permet le droit de la consommation.'],
      ['Droit de rétractation (UE/RU)', 'Lorsqu’un droit légal de rétractation s’applique à un achat de services numériques, tu peux demander l’annulation dans le délai légal. En démarrant un abonnement d’hébergement, tu nous demandes de commencer le service immédiatement, ce qui peut réduire ou supprimer ce droit de rétractation pour la part déjà fournie — comme le permet le droit de la consommation.'],
      ['Comment demander un remboursement', 'Contacte-nous via la page Contact avec l’e-mail de ton compte et la date/le montant approximatif du débit. Nous répondons sous quelques jours ouvrés. Les remboursements approuvés sont renvoyés sur le moyen de paiement d’origine via Stripe.'],
      ['Oppositions bancaires (chargebacks)', 'Si quelque chose semble anormal, contacte-nous d’abord — nous résolvons presque toujours plus vite qu’un litige bancaire. Ouvrir un chargeback sans nous contacter peut entraîner la suspension du compte et des dépôts associés en attendant résolution.'],
    ] },
  },
};

const LEGAL_SUMMARY = {
  en: {
    privacy: 'What data we collect, why we keep it, and the GDPR rights you can exercise at any time.',
    terms: 'The rules for using BetterCommunity, moderation, and the strict copyright rules for hosted content.',
    cookies: 'One essential sign-in cookie, plus optional privacy-friendly first-party analytics — no third parties.',
    about: 'Who we are, the Better* projects, and what BetterCommunity is here to do.',
    refunds: 'How billing works, the free tier, cancellation, and exactly when a refund applies.',
  },
  fr: {
    privacy: 'Les données que nous collectons, pourquoi, et les droits RGPD que tu peux exercer à tout moment.',
    terms: "Les règles d'utilisation de BetterCommunity, la modération, et les règles strictes de droits d'auteur pour le contenu hébergé.",
    cookies: 'Un seul cookie de session essentiel, plus des statistiques internes optionnelles et respectueuses — aucun tiers.',
    about: 'Qui nous sommes, les projets Better*, et la raison d’être de BetterCommunity.',
    refunds: 'Le fonctionnement de la facturation, l’offre gratuite, la résiliation, et quand un remboursement s’applique.',
  },
};

// When these texts last actually changed. A real date, edited with the text — the header
// used `new Date()`, so every one of these pages claimed to have been updated today, every
// day, whatever it said. On a policy page that is the one line a reader uses to decide
// whether the terms they agreed to are still the terms in front of them.
const LEGAL_UPDATED = '2026-08-14';

export function Legal({ page }) {
  const { lang, t } = useI18n();
  const d = (LEGAL[lang] || LEGAL.en)[page];
  const summary = (LEGAL_SUMMARY[lang] || LEGAL_SUMMARY.en)[page];
  const tabs = [['about', t('foot.about', 'About'), Sparkles], ['privacy', t('foot.privacy'), Lock], ['terms', t('foot.terms'), ShieldCheck], ['cookies', t('foot.cookies'), Cookie], ['refunds', t('foot.refunds', 'Payments'), Receipt]];
  return (
    <div className="max-w-4xl mx-auto">
      <PageHeader icon={d.icon} title={d.title} subtitle={`${lang === 'fr' ? 'Mis à jour le' : 'Last updated'} ${new Date(`${LEGAL_UPDATED}T00:00:00`).toLocaleDateString()}`} />
      <div className="flex flex-wrap gap-2 mb-5"><Link to="/legal"><Button size="sm" variant="default"><FileText size={14} /> {t('legal.all', 'All')}</Button></Link>{tabs.map(([k, l, I]) => <Link key={k} to={`/legal/${k}`}><Button size="sm" variant={k === page ? 'primary' : 'default'}><I size={14} /> {l}</Button></Link>)}</div>
      {/* plain-language summary */}
      <Card className="p-4 mb-6 flex items-start gap-3 bg-gradient-to-r from-[var(--primary)]/10 to-transparent">
        <d.icon size={18} className="text-[var(--primary-2)] mt-0.5 shrink-0" />
        <div className="text-sm text-[var(--muted)]">{summary}</div>
      </Card>
      <div className="grid md:grid-cols-[180px_1fr] gap-8">
        <nav className="hidden md:block sticky top-20 self-start space-y-0.5">
          <div className="text-[10px] font-semibold uppercase tracking-wider text-[var(--faint)] mb-1.5">{lang === 'fr' ? 'Sur cette page' : 'On this page'}</div>
          {d.body.map(([h], i) => <a key={h} href={`#s${i}`} className="block text-sm text-[var(--muted)] hover:text-[var(--primary-2)] py-1 border-l border-transparent hover:border-[var(--primary)] pl-2 -ml-px transition-colors">{h}</a>)}
        </nav>
        <Card className="p-6 md:p-8 space-y-7">
          {d.body.map(([h, p], i) => (
            <section id={`s${i}`} key={h} className="scroll-mt-24">
              <h2 className="text-lg font-semibold mb-2 flex items-center gap-2"><span className="text-[var(--primary-2)] font-mono text-sm">{String(i + 1).padStart(2, '0')}</span>{h}</h2>
              <p className="text-[var(--muted)] leading-relaxed">{p}</p>
            </section>
          ))}
          <div className="pt-4 border-t border-[var(--line)] text-sm text-[var(--muted)]">{lang === 'fr' ? 'Des questions sur cette politique ? Contacte-nous via les liens du pied de page.' : 'Questions about this policy? Reach us via the links in the footer.'}</div>
        </Card>
      </div>
    </div>
  );
}

// The /legal hub — lists every legal/policy document.
export function LegalIndex() {
  const { lang, t } = useI18n();
  const L = LEGAL[lang] || LEGAL.en;
  const S = LEGAL_SUMMARY[lang] || LEGAL_SUMMARY.en;
  const pages = ['about', 'privacy', 'terms', 'cookies', 'refunds'];
  return (
    <div className="max-w-4xl mx-auto">
      <PageHeader icon={FileText} title={t('legal.title', 'Legal & policies')} subtitle={t('legal.sub', 'Our policies and terms, in plain language.')} />
      <div className="grid sm:grid-cols-2 gap-4">
        {pages.map((k) => { const d = L[k]; const I = d.icon; return (
          <Link key={k} to={`/legal/${k}`} className="card card-hover p-5 flex items-start gap-3">
            <span className="grid place-items-center w-10 h-10 rounded-xl bg-[var(--surface-2)] text-[var(--primary-2)] shrink-0"><I size={18} /></span>
            <div className="min-w-0"><div className="font-semibold">{d.title}</div><div className="text-sm text-[var(--muted)] mt-0.5 line-clamp-2">{S[k]}</div></div>
          </Link>
        ); })}
      </div>
    </div>
  );
}
